### ISSUE TITLE
Integration Not Found

### ISSUE THREAD

**Issue by garyak** [PeteRager/lennoxs30#1]
Latest HAOS (2021.6.1) with `lennoxs30:` and cloud credentials in `configuration.yaml` and the directory lennoxs30 in custom_components.
![lennoxs30](https://user-images.githubusercontent.com/47036329/120868294-f8f82680-c550-11eb-9150-839937fdf3a3.jpg)
s.

**Comment by PeteRager** [comment]
I’ll do some experimentation to see if I can get that error and what HA specifically looks for.  I think it just looks for the presence of  __init.py__ 

so something like this 

haconfig/custom_components/lennoxs30/__init__.py

there should also be climate.py, s30api_async.py, manifest.json in that directory.

please post a screen shot of the directory.

**Comment by garyak** [comment]
Here you go:
![lennoxdir](https://user-images.githubusercontent.com/47036329/120891948-b7a35d80-c5c8-11eb-90e7-44820f346e85.jpg)

**Comment by PeteRager** [comment]
That certainly looks correct.

**Comment by PeteRager** [comment]
Do you have other custom components that work?

This article talks about permission problems:

https://community.home-assistant.io/t/custom-component-not-found/99227

Basically it should use the string from the configuration.yaml file

lennoxs30:

and try to load from a directory called custom_components/lennoxs30

**Comment by PeteRager** [comment]
i have not tried it on 2021.6.1, i will do that tonite

**Comment by garyak** [comment]
Yes, several. File permissions are 744.

**Comment by PeteRager** [comment]
I tried in on 2021.6.1 last night and it works fine for me,  I’ll try a few more things later today.

Any information in the log file?  have you tried restarting the container?

**Comment by garyak** [comment]
Have it running after I updated to 2021.6.2. Just didn't restart enough I guess. Climate sensors are being created. However, sensors for inactive zones report as unavailable instead of current temp. Two sensors are created to describe the s30 and lennox zone.  I have an s30 in the Kitchen and have a climate sensors for Kitchen and one for South (the Kitchen thermostat zone), This may be due to my hap-hazard naming scheme.

Anyway,  it's running. I'll setup a few cards to monitor the output. Thank you for taking this on. Homekit Controller is problematic with my setup.

**Comment by PeteRager** [comment]
Great news.  I just had recreated the issue by putting the custom_component in without restarting.  I'll update those notes.

Please log issues for those other items and we can close this issue?

I'm actively working on the next set of things.  I only have 1 zone, so I've never seen a multi-zone system.  Really interested in understanding details of what works and doesn't

**Comment by garyak** [comment]
Will do.

**Comment by PeteRager** [comment]
On the issue with the two non working sensors.  We should be able to get it to work.

I'll need the following:
- Turn debug on for this component in configuration.yaml - configuration is in the readme.
- FIre up the lennox app on your phone if you have it (so we can grab some screen shots of what the app shows the data as)
- Restart HA, wait for it to come up, let it run for ~5 minutes
- Grab the log file
- Grab some screen shots from the lennox app that shows the missing data
- Create an issue and post that stuff with it.

**Comment by garyak** [comment]
I’ll get all that together and open a new issue.
