### ISSUE TITLE
Add Lennox Images to Home Assistant Brands

### ISSUE THREAD

**Issue by PeteRager** [PeteRager/lennoxs30#104]
This is a requirement for full integration with HACS and needed for config_flows.

**Comment by GaryOkie** [comment]
Hi Pete,

Here are some suitable icons/logos for your S30 integration that follow the [custom integration branding requirements.](https://github.com/home-assistant/brands#readme) .    

Hope this helps you out to close this old issue!  

[lennoxS30_icons.zip](https://github.com/PeteRager/lennoxs30/files/9678168/lennoxS30_icons.zip)

**Comment by PeteRager** [comment]
Thank you!

**Comment by PeteRager** [comment]
https://github.com/home-assistant/brands/pull/3866

**Comment by PeteRager** [comment]
Icons have been accepted should start seeing them appear and browser caches expire.
