### ISSUE TITLE
Mode Switching Irregularities

### ISSUE THREAD

**Issue by garyak** [PeteRager/lennoxs30#11]
Switching modes in any one zone effects modes in other zones on multi-zone installations. Log to follow.

![lennoxzones](https://user-images.githubusercontent.com/47036329/121009272-31665300-c751-11eb-8ea9-28ce21062350.jpg)

**Comment by PeteRager** [comment]
Thanks.  I have a similar issue with Temperature setting; where setting it on 1 zone affects all zones, that I just finished fixing.  I'll get on this one next.

**Comment by PeteRager** [comment]
Yes it is the exact same issue.  i have a fix coded, will need some time to test it.  Should have something tomorrow.

**Comment by PeteRager** [comment]
Actually went faster than I thought 👍 

Give this branch a try:

https://github.com/PeteRager/lennoxs30/tree/2021.06.11/custom_components/lennoxs30

Copy these files over the old ones and restart HA.

This should fix:  
- The issue you reported on HVAC Mode
- A similar issue for FAN Mode
- A similar issue for setting the target temperature

Also adds support for using presets (aka  schedules).   Changing any of those three items when running a schedule; creates a schedule override.  To remove the override there is a special preset called Cancel Overrides

Let me know if this fixes the issue and I'll promote this to release 0.0.2

**Comment by garyak** [comment]
I've tested all four zones and, so far, modes function independently. Great work! I'll need to sharpen my lovelace skills to test scheduling and fan settings.
