### ISSUE TITLE
[Help Needed] Air Handler CFM Setpoint support 

### ISSUE THREAD

**Issue by PeteRager** [PeteRager/lennoxs30#110]
There are systems that have variable speed air handlers.  So for example, when the fan is on, there is a system setting to specify the CFM the fan should output.  This enhancement would expose this setting and allow it to be set.

**Comment by PeteRager** [comment]
There is an attribute on the climate entity called “demand”, this is the CFM that is active on the zone. Take a look at that, let me know if you get data.  You can create a template sensor to pull the attribute out into its own sensor.

**Comment by dcj** [comment]
I am currently running  V 0.0.5 and what I currently see is:
`demand: 0`
I will update to the latest release (seems like generally a good idea), and see if I get any data here.

**Comment by PeteRager** [comment]
Sounds good. Let me know what you see.   You should only see Demand = 0 when the zone is not calling for heating or cooling. If it’s actively heating or cooling it should have a non zero number.

**Comment by dcj** [comment]
OK, I made it through the update to v0.1.3a, see #119

**Comment by HyperActiveJ** [comment]
Pete is right,
It seems possible to do this.
![image](https://user-images.githubusercontent.com/6298301/181796775-57f67c1a-d68e-4afa-ae80-c2052e0c8c68.png)

The way we can add it to this intergration is
1. Install the dealer app in a VM or PC based android development environment: https://play.google.com/store/apps/details?id=com.lennox.iC3.dealermobile.droid&hl=en&gl=US
2.  Use pcap or similar to capture the data between the app and the HVAC.
3. Decrypt the data (its over HTPPS) - this is where i'm stuck, might need a proxy or something instead of pcap. 
4. Back out the commands being send to control the airflow.

@hufman  did this perviously, if i undersatnd correctly. His work is where i found the local https info and decoded the diag data. He may be able to provide more insight.

https://github.com/hufman/lennox_lcc

**Comment by hufman** [comment]
To clarify, I merely did static reverse engineering of the dealer app, and then poked at the local api with curl, and didn't do any HTTPS interception. I would expect this data to be available through the zone status though, and my repo has a few scripts to help dump the data out and see what it looks like!

**Comment by PeteRager** [comment]
I like that idea of setting it up in android dev environment.  Here’s what I’ve found / tried so far..

I’ve been able to trick the dealer app into connecting to my WIFI, I have an old WiFi router set in bridge mode connected into a PFSense gateway. 

1. setup a WiFi network called DIRECT-XY12-3456, connect iPad to it. 
2. The dealer app tries to connect to a hard coded IP addresses, one of them is 17.57.147.5
3. I tried configuring a NAT to redirect this to the S30 IP address,  this did not seem to work…so instead…
4. configured the iPad http proxy to redirect to a BURP proxy on my PC, and then configured the Burp Proxy to redirect to the S30, this kind of worked, in that I could see the App calling the end point to retrieve messages but the S30 was returning a 400 because the app had not called the endpoint to setup the subscription.  So it polls for messages for 15-30 seconds then gives up and declares that it is not connected.

The next thing to try is to manually setup that subscription, by calling the endpoint directly, and see if this makes the App happier.

**Comment by PeteRager** [comment]
I'm pretty sure this is the message to be sent:

```
{
    "systemControl":
    {
        "parameterUpdate" : 
        {
            "et" : "equipment type code",
            "pid" : "parameter id",
            "value": "str"
        }
    }
}
```

Where et is the equipment type code which we get in the equipment message, pid is the parameter id.  

I found this list of et codes

```
      SYSTEM(0),
        FURNACE(16),
        AIR_HANDLER(17),
        AIR_CONDITIONER(18),
        HEAT_PUMP(19),
        ZONING_A(22),
        ZONING_B(23),
        PURE_AIR(28),
        COMFORT_SENSOR(64),
        THERMOSTAT(500),
        BASE(501),
        APPMAN(502),
        OS(503),
        WIFI(504),
        UNKNOWN(505),
        HOMEKIT(506),
```

You'd then want to send it using the same mechanism used to set the diagnostic level. 

```
    async def set_diagnostic_level(self, level: int) -> None:
        level = int(level)
        _LOGGER.debug(f"set_diagnostic_level sysid [{self.sysId}] level[{level}]")
        if level not in (0, 1, 2):
            raise S30Exception(
                f"Invalid diagnostic level [{level}] valid value [0,1,2]",
                EC_BAD_PARAMETERS,
                1,
            )
        ## Put the parameterUpdate structure in here rather than diagControl
        data = '"Data":{"systemControl":{"diagControl":{"level":' + str(level) + "} } }"
        await self.api.publishMessageHelper(self.sysId, data)
        # The S30 does not send message when the systemControl parameters are update, but if we re-ask
        # for the systemControl subscription, it will send us the current data.
        await self.api.requestDataHelper(
            self.sysId,
            '"AdditionalParameters":{"JSONPath":"/systemControl"}',
        )
```

So I think it boils down to this (untested, unsyntax tested)
```
    async def set_eq_paramater(self, et:int, pid:int, value:str) -> None:
        command = {"systemControl": {"parameterUpdate": {"et": et, "pid" : str(pid), "value" : str(value)}}}
        await self.api.publish_message_helper_dict(self.sysId, command)
```

I'm not near my S30 for  a while..

**Comment by PeteRager** [comment]
Command Sent:

```
2022-08-14 16:09:01,060 [MainThread  ] [DEBUG]  {
    "MessageType": "Command",
    "SenderID": "**redacted**",
    "MessageID": "00000000-0000-0000-0000-000000000003",
    "TargetID": "LCC",
    "Data": {
        "systemControl": {
            "parameterUpdate": {
                "et": 17,
                "pid": 19,
                "value": "565"
            }
        }
    }
}
```
Responses

```
2022-08-14 16:09:08,642 [MainThread  ] [DEBUG]  {
    "messages": [
        {
            "MessageId": 0,
            "SenderID": "**redacted**",
            "TargetID": "ha_dev",
            "MessageType": "PropertyChange",
            "Data": {
                "system": {
                    "status": {
                        "rsbusMode": "commissioning"
                    },
                    "publisher": {
                        "publisherName": "lcc"
                    }
                }
            }
        }
    ]
}

```
2022-08-14 16:09:08,681 [MainThread  ] [DEBUG]  {
    "messages": [
        {
            "MessageId": 0,
            "SenderID": "**redacted**",
            "TargetID": "ha_dev",
            "MessageType": "PropertyChange",
            "Data": {
                "system": {
                    "test": {
                        "list": [
                            {
                                "test": {
                                    "tid": 0,
                                    "explanation": "Check Blower Operation",
                                    "name": "Blower"
                                },
                                "id": 0
                            },
                            {
                                "test": {
                                    "tid": 10,
                                    "explanation": "Check Min Rate Cooling Operation",
                                    "name": "Cooling - Minimum Rate"
                                },
                                "id": 1
                            },
                            {
                                "test": {
                                    "tid": 12,
                                    "explanation": "Check Max Rate Cooling Operation",
                                    "name": "Cooling - Maximum Rate"
                                },
                                "id": 2
                            }
                        ],
                        "szTest": 3
                    },
                    "publisher": {
                        "publisherName": "lcc"
                    }
                }
            }
        }
    ]
}

```
2022-08-14 16:09:08,812 [MainThread  ] [DEBUG]  {
    "messages": [
        {
            "MessageId": 0,
            "SenderID": "**redacted**",
            "TargetID": "ha_dev",
            "MessageType": "PropertyChange",
            "Data": {
                "equipments": [
                    {
                        "publisher": {
                            "publisherName": "lcc"
                        },
                        "equipment": {
                            "parameters": [
                                {
                                    "parameter": {
                                        "pid": 19,
                                        "enabled": true,
                                        "value": "565"
                                    },
                                    "id": 9
                                }
                            ],
                            "equipType": 17
                        },
                        "id": 2
                    }
                ]
            }
        }
    ]
}
```
```
```

**Comment by PeteRager** [comment]
@HyperActiveJ 

I have figured out how to get the dealer app working and log the messages.  I don't have a multizone system, so I don't get those controls and hence can't capture the messages to directly control the airflow.

It may require an iPad though, as I believe Android does not allow installing a BURP proxy cert?  Anyways the steps are:

1. Install the dealer app on iPad
2. Create a new wifi network, called DIRECT-XY12-3456 (the dealer app looks specifically for this and won't work on networks with any other names), this network should bridge into the network with your PC and S30,
3. Configure ipad to use that network
4. Install Burp Proxy (free edition) on PC, start it, go to options.  I configured it to run on port 8080, and opened this on the PC firewall for incoming.

![burpsetup_a](https://user-images.githubusercontent.com/76050312/187459101-962f9e65-be4d-46ef-853c-685abbb47c62.PNG)

Next, configure BURP proxy to route all traffic to the S30.

![burpsetup](https://user-images.githubusercontent.com/76050312/187459281-37ef53c3-e2c1-4271-9558-c78953a371da.PNG)

Turn BURP intercept off, otherwise it will pause on each request.

5. On the iPAD configure the proxy for the DIRECT-Xy12-* WIFI network, to be BURP on the PC, go to the BURP ip address in Safari and download / install the certificate onto the iPad - BURP docs describe this well.

6. Startup the dealer app, and you should see some traffic in BURP from it.  For me it calls the message endpoint which fails since it never established a subscription.  Don't know why, anyways in the URL you'll see the app_id  it should be DCA_nnnnnn, where nnnnn is some unique id of the app.  Copy this

7. In an HA dev environment, configure the integration to connect to the S30 and use DCA_nnnnn as the app_id, verify the integration work.

8. Stop HA, set a breakpoint here in the integrations __init__.py

![breakpoint](https://user-images.githubusercontent.com/76050312/187460948-869f76b3-8583-4dc6-8823-7e6f998934da.PNG)

9. Run HA, it'll establish the subscription, and leave it at the breakpoint so it doesn't consume messages
10. Restart the ipad app, it should connect and work.  BURP should capture the messages.

**Comment by PeteRager** [comment]
I pointed the Lennox Tool at the API simulator that has zoning configured.  Those controls just set the equipment parameters.

```
{"MessageType":"Command","SenderID":"dca_71824885284","MessageID":"00000000-0000-0000-0000-000000000009","TargetID":"LCC","AdditionalParameters":"\/systemControl","Data":{"systemControl":{"parameterUpdate":{"pid":272,"et":0,"value":"505"}}}}
```

**Comment by PeteRager** [comment]
Release is here:

https://github.com/PeteRager/lennoxs30/releases/tag/2022.9.0
