### ISSUE TITLE
Can not install Lennox30 integration even through HACs shows it in integrations

### ISSUE THREAD

**Issue by kkolkebeck** [PeteRager/lennoxs30#141]
So, I went through and installed HACs and using the Community store I found the Lennox30 integration and added it. Now in my HACS integrations, the Lennox iComfort Component shows up. When I go to HASS integrations and attempt to Add an integration the Lennox integration does not show up. I have rebooted HASS a couple of times but nothing seems to matter. Getting the integration from the HACS integrations to the HASS integrations does not seem to be working.

**Comment by PeteRager** [comment]
We should be able to get it working via HACS,  most people have it installed that way.  

What version of HA are you on?

There are HACS installation instructions in readme, which step are you on?

HACS should place the component into the custom_components folder.  Do you see a lennoxs30 subfolder in there?

**Comment by kkolkebeck** [comment]
Version 2022.2.6
Completed "Add custom repository in HACS and also Add integration in HACS
Repository has two folders- lennoxs30 and myicomfort.

**Comment by kkolkebeck** [comment]
Given I have an S30 I got rid of the myicomfort after reading the instructions which said it would not work with S30.

**Comment by PeteRager** [comment]
Try going into HA, select Configure, select integrations, select add then see if you can find Lennox

**Comment by kkolkebeck** [comment]
That's exactly where I am stuck. When I do that and enter Lennox in the search field it tells me "no integrations matched your search......."

**Comment by PeteRager** [comment]
Got it.

So I think this is what happened.  

While this component is called Lennox S30, the Hacs description is “Lennox iComfort Component”.  And hence if you deleted that, it could be the issue.  

Retry those first steps, see if that resolves it.

**Comment by kkolkebeck** [comment]
It didn't work when I had them both installed but will try again. 
Ken Kolkebeck
"Trust is built in drops and lost in buckets". Kevin Plank
 

    On Tuesday, February 15, 2022, 05:42:20 PM EST, PeteRager ***@***.***> wrote:  
 
 


Got it.

So I think this is what happened.

While this component is called Lennox S30, the Hacs description is “Lennox iComfort Component”. And hence if you deleted that, it could be the issue.

Retry those first steps, see if that resolves it.

—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by kkolkebeck** [comment]
That wasn't the problem. Plus, it does not make sense to me given what I get for the iComfort WiFi Component-



Ken Kolkebeck
"Trust is built in drops and lost in buckets". Kevin Plank
 

    On Tuesday, February 15, 2022, 05:42:20 PM EST, PeteRager ***@***.***> wrote:  
 
 


Got it.

So I think this is what happened.

While this component is called Lennox S30, the Hacs description is “Lennox iComfort Component”. And hence if you deleted that, it could be the issue.

Retry those first steps, see if that resolves it.

—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by PeteRager** [comment]
I have not tried it with 2022.2.6.  I can get that setup in a day or two. 

We could try the alternate install, grab the zip file, drop the components in and restart HA

**Comment by kkolkebeck** [comment]
Should I delete it from HAC first? 
Ken Kolkebeck
"Trust is built in drops and lost in buckets". Kevin Plank
 

    On Tuesday, February 15, 2022, 06:10:12 PM EST, PeteRager ***@***.***> wrote:  
 
 


I have not tried it with 2022.2.6. I can get that setup in a day or two.

We could try the alternate install, grab the zip file, drop the components in and restart HA

—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by PeteRager** [comment]
Good question.  Let’s delete it.

**Comment by PeteRager** [comment]
Getting setup to test.   Did manual install work?

**Comment by kkolkebeck** [comment]
I've not had a block of time to play with it. Hopefully this afternoon. I'm on UTC -5 time. 
Ken Kolkebeck
"Trust is built in drops and lost in buckets". Kevin Plank
 

    On Wednesday, February 16, 2022, 11:16:35 AM EST, PeteRager ***@***.***> wrote:  
 
 


Getting setup to test. Did manual install work?

—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by PeteRager** [comment]
Sounds good.

I have validated it with 2022.2.7 - which is the latest - using a manual install.  Next step I'll get HASS setup

**Comment by kkolkebeck** [comment]
Should I wait so I can validate the HASS setup? I'm in no rush. 
Ken Kolkebeck
"Trust is built in drops and lost in buckets". Kevin Plank
 

    On Wednesday, February 16, 2022, 12:33:54 PM EST, PeteRager ***@***.***> wrote:  
 
 


Sounds good.

I have validated it with 2022.2.7 - which is the latest - using a manual install. Next step I'll get HASS setup

—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by kkolkebeck** [comment]
The instructions for manual installation seem straightforward enough. I don't want to sound like an idiot but it is not entirely clear how to copy the extracted contents of the zip file into the custom_components section. I do this in terminal mode? If so I rarely use the commands since my dos days. 
Ken Kolkebeck
"Trust is built in drops and lost in buckets". Kevin Plank
 

    On Wednesday, February 16, 2022, 12:35:24 PM EST, ken kolkebeck ***@***.***> wrote:  
 
 Should I wait so I can validate the HASS setup? I'm in no rush. 
Ken Kolkebeck
"Trust is built in drops and lost in buckets". Kevin Plank
 

    On Wednesday, February 16, 2022, 12:33:54 PM EST, PeteRager ***@***.***> wrote:  
 
 


Sounds good.

I have validated it with 2022.2.7 - which is the latest - using a manual install. Next step I'll get HASS setup

—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by PeteRager** [comment]
I tested it with HACS and it worked for me.  The HACS UI did change a bit and the specific instructions may need an update.

First I did these steps from the readme:

Click on HACS in your menu to open the HACS panel, then click on integrations (https://your.domain/hacs/integrations).
Click on the 3 dots in the top right corner.
Select "Custom repositories"
Add the URL to the repository: https://github.com/PeteRager/lennoxs30
Select the integration category.
Click the "ADD" button.

Then then brought me to this series of UI:

![hacs_1](https://user-images.githubusercontent.com/76050312/154328169-9a6a0933-ddea-44b6-a557-0dce00c47c86.PNG)

In the above screen I clicked Download.  This is the step that actually downloads the component.  The prior steps simply register it.

![hacs_2](https://user-images.githubusercontent.com/76050312/154328195-7e5b59ff-b080-4588-b499-aae216245453.PNG)

After clicking download it brought up this dialog, I just accepted the defaults.

![hacs_3](https://user-images.githubusercontent.com/76050312/154328211-ec1ae744-c87f-46e0-bf74-e80ac56bb013.PNG)

It then tells me to restart HA which I did

![hacs_4](https://user-images.githubusercontent.com/76050312/154328228-d4c1342d-6a1b-488c-a81a-2ab42cd667f6.PNG)

After a restart it looks like this

![hacs_5](https://user-images.githubusercontent.com/76050312/154328248-a9d16eb5-3c8b-4d1c-a193-74f0b0bfae8d.PNG)

Then I went into Configure / Integrations and was able to find the integration.

Give these steps a try.  And capture screen shots along the way if it is looking different for you.

**Comment by kkolkebeck** [comment]
Thank you Pete. That worked. Very cool application and I like the fact that I can get at the mode, schedule selection, and fan settings through the app. I had been using the homekit interface and frankly it just did not work at all. It only allowed me to change the setpoint which threw the S30 into a hold setting. 
I set the flag for the inverter power. Tell me, what is the inverter power functionality? I get a "unknown" listed for a value. Also, what is the "diagnostic_level"? I get a slide bar with a zero setting. 
One thing I have wanted to get out of my unit is the airflow volume but I don't know if this is possible as it does not show on the S30 display. I know the value is in the furnace because I can look at the display on the furnace controller itself and see it, albeit coded. Knowing the CFM, return, and supply temps I should be able to calculate the BTUs. 
I also don't have an OAT sensor installed so that just reads 77. Plan is just not to use the variables that don't function. 
Ken Kolkebeck
"Trust is built in drops and lost in buckets". Kevin Plank
 

    On Wednesday, February 16, 2022, 01:11:39 PM EST, PeteRager ***@***.***> wrote:  
 
 


I tested it with HACS and it worked for me. The HACS UI did change a bit and the specific instructions may need an update.

First I did these steps from the readme:

Click on HACS in your menu to open the HACS panel, then click on integrations (https://your.domain/hacs/integrations).
Click on the 3 dots in the top right corner.
Select "Custom repositories"
Add the URL to the repository: https://github.com/PeteRager/lennoxs30
Select the integration category.
Click the "ADD" button.

Then then brought me to this series of UI:



In the above screen I clicked Download. This is the step that actually downloads the component. The prior steps simply register it.



After clicking download it brought up this dialog, I just accepted the defaults.



It then tells me to restart HA which I did



After a restart it looks like this



Then I went into Configure / Integrations and was able to find the integration.

Give these steps a try. And capture screen shots along the way if it is looking different for you.

—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by kkolkebeck** [comment]
Actually, now I see that the inverter is in the "Outdoor Unit" which would be the condenser, provided I had a condenser with an inverter, or a heat pump. This clearly is not the inverter that controls fan speed, which my unit has. I therefore will not use either the outdoor temperature or the inverter power entities. 
Ken Kolkebeck
"Trust is built in drops and lost in buckets". Kevin Plank
 

    On Wednesday, February 16, 2022, 02:02:02 PM EST, ken kolkebeck ***@***.***> wrote:  
 
 Thank you Pete. That worked. Very cool application and I like the fact that I can get at the mode, schedule selection, and fan settings through the app. I had been using the homekit interface and frankly it just did not work at all. It only allowed me to change the setpoint which threw the S30 into a hold setting. 
I set the flag for the inverter power. Tell me, what is the inverter power functionality? I get a "unknown" listed for a value. Also, what is the "diagnostic_level"? I get a slide bar with a zero setting. 
One thing I have wanted to get out of my unit is the airflow volume but I don't know if this is possible as it does not show on the S30 display. I know the value is in the furnace because I can look at the display on the furnace controller itself and see it, albeit coded. Knowing the CFM, return, and supply temps I should be able to calculate the BTUs. 
I also don't have an OAT sensor installed so that just reads 77. Plan is just not to use the variables that don't function. 
Ken Kolkebeck
"Trust is built in drops and lost in buckets". Kevin Plank
 

    On Wednesday, February 16, 2022, 01:11:39 PM EST, PeteRager ***@***.***> wrote:  
 
 


I tested it with HACS and it worked for me. The HACS UI did change a bit and the specific instructions may need an update.

First I did these steps from the readme:

Click on HACS in your menu to open the HACS panel, then click on integrations (https://your.domain/hacs/integrations).
Click on the 3 dots in the top right corner.
Select "Custom repositories"
Add the URL to the repository: https://github.com/PeteRager/lennoxs30
Select the integration category.
Click the "ADD" button.

Then then brought me to this series of UI:



In the above screen I clicked Download. This is the step that actually downloads the component. The prior steps simply register it.



After clicking download it brought up this dialog, I just accepted the defaults.



It then tells me to restart HA which I did



After a restart it looks like this



Then I went into Configure / Integrations and was able to find the integration.

Give these steps a try. And capture screen shots along the way if it is looking different for you.

—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by PeteRager** [comment]
On inverter power, I may have it associated with the wrong device.  On my AC only system the inverter is outside.  That said, the inverter power is in alpha an requires setting Diagnostic Mode to 1 or 2 - however - that had been causing S30 instability issues (S30 reboots, S30 connectivity issues) for some users - so I would not recommend doing that until we get some run-time on your system and it is stable.

There is a Demand attribute on the climate entity and that is the CFM of demand for that zone.

**Comment by PeteRager** [comment]
I’d like to get a copy of your S30 config.  We should not create the outdoor sensor if the S30 does not have one.  At somepoint, turn on message logging and select an output file like s30_message.log (integration/configure), reload the integration and post that file or email it me (I can send you that if needed.)

I’ll update the docs to close this issue and then lets create 2 more issues:
1.  Inverter on the wrong device
2. Outdoor Temperature Sensor created when it does not exist.

Anything else?

**Comment by kkolkebeck** [comment]
I just disabled that which did not work. My outdoor unit is old school using hardwired signals rather than coms. I'll make an attempt to get what you ask for. 
If you could pull CFM data out of the air handler, that would be great. Even if you can't, I still love what you have done. 
Ken Kolkebeck
"Trust is built in drops and lost in buckets". Kevin Plank
 

    On Wednesday, February 16, 2022, 03:49:23 PM EST, PeteRager ***@***.***> wrote:  
 
 


I’d like to get a copy of your S30 config. We should not create the outdoor sensor if the S30 does not have one. At somepoint, turn on message logging and select an output file like s30_message.log (integration/configure), reload the integration and post that file or email it me (I can send you that if needed.)

I’ll update the docs to close this issue and then lets create 2 more issues:
   
   - Inverter on the wrong device
   - Outdoor Temperature Sensor created when it does not exist.

Anything else?

—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by kkolkebeck** [comment]
I saw this after. I don't seem to have a Demand attribute. 
Attached is my configuration, via a bunch of screen shots. I set up logs for the S30 although it isn't clear to me how I get to them. 
Ken Kolkebeck
"Trust is built in drops and lost in buckets". Kevin Plank
 

    On Wednesday, February 16, 2022, 03:43:20 PM EST, PeteRager ***@***.***> wrote:  
 
 


On inverter power, I may have it associated with the wrong device. On my AC only system the inverter is outside. That said, the inverter power is in alpha an requires setting Diagnostic Mode to 1 or 2 - however - that had been causing S30 instability issues (S30 reboots, S30 connectivity issues) for some users - so I would not recommend doing that until we get some run-time on your system and it is stable.

There is a Demand attribute on the climate entity and that is the CFM of demand for that zone.

—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by PeteRager** [comment]
Look in the developer tools.  Here is what the S30 climate entities all look like.  demand is what you want.  You can create a template sensor to pull it in {{ state_attr(“climate.zone_1”, “demand”) }} to a stand alone sensor.

Regarding getting the log files.  Easiest way it to first get ssh access to the device, then use a GUI like WINSCP to view the files.  You can also just enable debug for the component in configuration.yaml and it’ll dump the message into home assistants log file. The standalone log file is cleaner but either will be fine.   

>

**Comment by PeteRager** [comment]
![climate attrs](https://user-images.githubusercontent.com/76050312/154367021-1ba5a6b9-40b1-4335-86ac-f05d7f08769f.PNG)

**Comment by PeteRager** [comment]
![demand template](https://user-images.githubusercontent.com/76050312/154367351-ace89e1b-e546-4db1-ad19-aab6c96a673d.PNG)

**Comment by PeteRager** [comment]
My ac is turned off as its winter here, so demand is zero.

**Comment by PeteRager** [comment]
Ken a question for you regarding the outdoor temperature sensor, as I have a similar bug I'll be working on...

There should be a device created for the outdoor unit that has the temperature sensor attached to it.  For example, on my system which has an outdoor unit, the Device Info shows "air conditioner".  Since you don't have an outdoor device, what is shown in the Device Info?  I'm asking so that I can not created the outdoor temperature sensor if there is no outdoor unit, but I don't know string Lennox is going to put in the message.

                            "outdoorUnitType": "air conditioner",
                            "outdoorUnitStaging": 0,
                            "outdoorUnitCommunicating": true,

**Comment by kkolkebeck** [comment]
Here are my devices and entities. The “outdoor unit” is present but the associated entities are disabled. I can’t remember if I disabled them or if the installation figure out there was no outdoor unit. 


Ken

**Comment by PeteRager** [comment]
Did you intend to provide a screen shot - it did not come through?

**Comment by kkolkebeck** [comment]
Yes. I’ll try again. 


Ken
