### ISSUE TITLE
Thermostat IP address changed. How can I reassign it to integration?

### ISSUE THREAD

**Issue by kkolkebeck** [PeteRager/lennoxs30#143]
The Lennox integration has been terrific and running bug free for several months. However, I can not seem to set a static IP address at the S30, and while I set one at the router, the S30 is behind an extender and so the IP address recently changed on a reboot. I have been unable to find where the address is in the integration. I see it in the title and changed it there, but even after a restart of the integration and HAS, that did not make a difference. I looked the the configuration files but could not find it.
Can you point me in the right direction? Or do I need to reload the entire integration?

**Comment by PeteRager** [comment]
Great question.  Ideally the IP would remain static in your system.   Right now the IP address is not editable in the UI after it’s been configured and you are the second person who has asked for this - and hence it seems like a worthy enhancement.   

Right now though, you can manually edit it.   In your config directory there is a folder called “.storage”, in that folder there is a file called “core.config_entries”, within that file is where the IP address is configured.  

You should find an entry like this, the title doesn’t matter, update “host” to the new IP address.  Follows these steps if possible

- stop home assistant
- Create a backup copy of the core.config_entries
- Edit file and update host to new iP
- Restart home assistant

It may be possible to make the edit while HA is running and then select reload integration.  HA does some caching of this file, so it’s also possible it won’t pick up the change or may overwrite the change later.


           {
                "entry_id": "c18f900b2b79d7feeedfc0f9801c7860",
                "version": 2,
                "domain": "lennoxs30",
                "title": "192.168.1.93",
                "data": {
                    "app_id": "ha_prod",
                    "create_sensors": true,
                    "allergen_defender_switch": false,
                    "create_inverter_power": false,
                    "scan_interval": 1,
                    "init_wait_time": 30,
                    "fast_scan_interval": 0.5,
                    "protocol": "https",
                    "pii_in_message_logs": false,
                    "message_debug_logging": true,
                    "log_messages_to_file": true,
                    "message_debug_file": "s30_message.log",
                    "host": "192.168.1.93",
                    "cloud_connection": false,
                    "fast_scan_count": 10,
                    "timeout": 30
                },
                "options": {},
                "pref_disable_new_entities": false,
                "pref_disable_polling": false,
                "source": "import",
                "unique_id": "lennoxs30_192.168.1.175",
                "disabled_by": null
            },

**Comment by PeteRager** [comment]
The other option is to delete the integration and re-add.   The only issue will be if you have renamed the entity ids or names that configuration will be lost and will need to be done again.

**Comment by PeteRager** [comment]
Folders that start with a “.” are hidden by some tools.   You’ll need to find a way to unhide it in the tool you are using.  I use WINSCP.   Here’s how to view hidden files in it and some other tools

https://www.lcn.com/support/articles/how-to-show-hidden-files-in-ftp/

**Comment by kkolkebeck** [comment]
Appreciate it. Thank you. 
Ken Kolkebeck
"Trust is built in drops and lost in buckets". Kevin Plank
 

    On Tuesday, March 8, 2022, 12:15:47 PM EST, PeteRager ***@***.***> wrote:  
 
 


Folders that start with a “.” are hidden by some tools. You’ll need to find a way to unhide it in the tool you are using. I use WINSCP. Here’s how to view hidden files in it and some other tools

https://www.lcn.com/support/articles/how-to-show-hidden-files-in-ftp/

—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by kkolkebeck** [comment]
I found a more straightforward work around that is a more permanent fix because each time the router reassigns an IP, it will consistently be the one the Lennox integration is expecting. I found that, unlike what my memory told me, I had not set the Lennox address as a static IP address. Here is what I did.    
   - If you don't remember the original IP the integration was set for, that address is in the header of the Lennox S30/E30 integration configuration tool. 
   - I retrieved the MAC address from the Lennox S30, which you have to dig to find. This is available by going to settings, wifi settings, then clicking on the wifi network the unit is connected to, then clicking on the information link to the right. 
   - I then deactivated the wifi on the S30.
   - Then, using the MAC address I set a static IP address using the DHCP Server settings of my primary router. 
   - I updated the settings and rebooted the router. 
   - Then activated the wifi on the S30, selected the extender network, then logged in credentials.
   - Once the wifi connection was reestablished, the S30 obtained the IP address I had originally set in the Lennox integration. 
   - The interface worked at once. 
For your other user who had problems with a changing IP address, setting the address as the static address home assistant is looking for will cure the problem and prevent it from happening again. 
Thank you for your help.  Ken Kolkebeck
"Trust is built in drops and lost in buckets". Kevin Plank
 

    On Tuesday, March 8, 2022, 09:45:43 AM EST, PeteRager ***@***.***> wrote:  
 
 


The other option is to delete the integration and re-add. The only issue will be if you have renamed the entity ids or names that configuration will be lost and will need to be done again.

—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by PeteRager** [comment]
Great, having a permanent IP is the best approach, glad it is solved.  I’ll close this as an issue.
