### ISSUE TITLE
KeyError: "fast_scan_count"

### ISSUE THREAD

**Issue by peterwin97** [PeteRager/lennoxs30#147]
Hello I have two M30 thermostats in my home and have been having trouble getting it set up with HA. Below is the error log from HA. Any assistance would be appreciated.

> This error originated from a custom integration.
> 
> Logger: homeassistant.config_entries
> Source: custom_components/lennoxs30/__init__.py:251 
> Integration: Lennox S30/E30 (documentation, issues) 
> First occurred: 14:40:36 (1 occurrences) 
> Last logged: 14:40:36
> 
> Error setting up entry Petern_uy_n2_97@gm_il.co_ for lennoxs30
> Traceback (most recent call last):
>   File "/usr/src/homeassistant/homeassistant/config_entries.py", line 335, in async_setup
>     result = await component.async_setup_entry(hass, self)
>   File "/config/custom_components/lennoxs30/__init__.py", line 251, in async_setup_entry
>     fast_poll_count = entry.data[CONF_FAST_POLL_COUNT]
> KeyError: 'fast_scan_count'
>

**Comment by PeteRager** [comment]
That looks like a bug.  That configuration parameter was added in the last release, but it was omitted from the config flow when creating a cloud connection.  

However, you can fix the issue by manually editing the home assistant configuration file.

The configuration for the connection is stored in .storage/core.config_entries  - I'd recommend stashing a copy of the file before you edit it.  In these you'll find the configuration.  Search for "lennoxs30"

Here's an example of what mine looks like for a local connection.  Your configuration will be slightly different since its a cloud connection.
```
            {
                "entry_id": "c18f900b2b79d7feeedfc0f9801c7860",
                "version": 2,
                "domain": "lennoxs30",
                "title": "192.168.1.93:4343",
                "data": {
                    "app_id": "ha_prod",
                    "create_sensors": true,
                    "allergen_defender_switch": false,
                    "create_inverter_power": false,
                    "scan_interval": 1,
                    "init_wait_time": 30,
                    "fast_scan_interval": 0.5,
                    "protocol": "https",
                    "pii_in_message_logs": false,
                    "message_debug_logging": true,
                    "log_messages_to_file": true,
                    "message_debug_file": "s30_message.log",
                    "host": "192.168.1.93:4343",
                    "cloud_connection": false,
                    "fast_scan_count": 10,
                    "timeout": 30
                },

```

Based on the error and looking at the code, I would expect the "fast_scan_count" is not in the configuration, so you'll want to add that "fast_scan_count" in.  Take the line from the above file and paste it in.

**Comment by PeteRager** [comment]
Looking at the bug a bit more.  It looks like this occurs if you go into Options after configuring the integration?   Do you recall if you did that?  If so another temporary solution could be to delete the integration, reconfigure it and don't go into options.

**Comment by PeteRager** [comment]
I have the bug fixed.  The bug occurs when selecting Configure after the integration is first configured.  It omits the "fast_scan_count" and the "timeout".  So you can edit as described above and add both of these.  Or delete the integration and re-add it.

I should have an new release available tomorrow that fixes this issue.

**Comment by peterwin97** [comment]
Thanks Pete for you quick response. I was able to get past the error. Now all I can assume is everything is working fine since there are no errors in HA, but I only see one entity under it named "state" and no devices. Shouldn't I be able to take control of my thermostats using this plugin?

**Comment by PeteRager** [comment]
Yes, it should create climate entities for each M30. Does the state entity report “Connected”?   

If it’s not we may need to enable debug logging, restart HA and see what exactly is going on.

https://github.com/PeteRager/lennoxs30#reporting-bugs

**Comment by peterwin97** [comment]
<img width="405" alt="image" src="https://user-images.githubusercontent.com/15694968/164285416-df50d03d-9648-4f84-9c4b-05828e5d0844.png">

It does show that it is connected yes.

**Comment by PeteRager** [comment]
That’s good news.  Let’s grab the debug logs and we should be able to see what is going on.

**Comment by PeteRager** [comment]
That timeout value I has you configure may be too low for a cloud connection. Did you do the manual edit and set it to 30? For cloud it should be set to 60.

**Comment by peterwin97** [comment]
Okay I changed the timeout value to 60 and now its staying connected. I checked in developer tools and there are no climate entities in there. I am able to control using the Lennox app

**Comment by PeteRager** [comment]
Ok.  Let’s get those debug logs.   Restart HA, let it run for 4-5 minutes, grab the log. And post or you can email to me.

**Comment by peterwin97** [comment]
email address?

**Comment by PeteRager** [comment]
Pete dot sage at iCloud dot com

**Comment by peterwin97** [comment]
Email has been sent.

**Comment by PeteRager** [comment]
Did not get it.

**Comment by peterwin97** [comment]
apologies, had a typo. should be sent now

**Comment by PeteRager** [comment]
Got the email, no attachment.  Try again?

**Comment by peterwin97** [comment]
Oops, tried it again. Forgot to attach It on the original email.

**Comment by PeteRager** [comment]
Thanks for the log.   The good news is it is connecting and getting a lot of data from Lennox.

What I see is that you have two thermostats but the integration is only receiving configuration for 1 of the thermostats.  Then it times out and restarts the whole process.

This information indicates one of the thermostats is offline

    "myPresence": {
        "2cee9e8e-8498-47f0-93e8-6ac992edfff8": "online",
        "c7a86db1-0613-4851-8320-cbab8310f444": "offline"
    }

The thermostat that came through has the name

          "name": "House",

Which may just be the default.  

Next steps:
- check the WiFi setup on the thermostats, one of them is disconnected 
- In the Lennox app, you should only be able to access and control 1 of the thermostats
- Consider setting the name in the thermostats to be different - as these names will be used in home assistant


Once fixed, you should see that presence be online for both and the entities should get created.  

On my end this has revealed a couple of issues that we’ll want to fix:
- integration should complete setup for the 1 thermostat that it did get configuration for vs. it’s current behavior of failing for both.
- Integration should look at that presence information and generate an error when one is offline and present this info rating during initial setup.

**Comment by PeteRager** [comment]
Tracking for the issues in the integration regarding the offline device and need for better error reporting.

https://github.com/PeteRager/lennoxs30/issues/148

I’ll put these in an upcoming patch release, but we may do this separate from this configuration error.  Anyways we’ll make those decisions once you are online and running.

**Comment by PeteRager** [comment]
One more note, as I'll be away for a bit this morning.

The name of your house (modified here to protect your information)

"name": "620 Somethingchase",

Has an embedded space in it.  When I initially saw that, I though that was the issue.  I don't know if it will cause an issue or not and have not been able to test it out yet.  This name goes into the Entity_ID in home assistant; perhaps it will remove the space for us or it may not.   I will test this at some point.  You could certainly change it and remove the space or stick an underscore in; alternatively don't change it and if everything comes up once that off-line thermo is fixed we'll know its fine.

Pete

**Comment by peterwin97** [comment]
Ok, so I went back and reconfigured all my thermostats. For some reason one decided to not connect to the internet anymore. Now everything is working great and I am able to control climate through HA and HomeKit

**Comment by PeteRager** [comment]
That is great news.  Let me know if you run into any other issues.   Now that you are online. I’ll get a patch out for this configuration problem as soon as I can.  

Then in the next release I’ll improve the diagnostics and error reporting when a device is offline, as described in #148

**Comment by PeteRager** [comment]
This issue is resolved in this release.  Let me know if you have further issues

https://github.com/PeteRager/lennoxs30/releases/tag/v0.2.5
