### ISSUE TITLE
messagePump unknown SenderId/SystemId

### ISSUE THREAD

**Issue by ziz480** [PeteRager/lennoxs30#153]
First of all, thank you for all your work here!

I keep seeing the following error message in my HA logs - it's being emitted every second (sometimes 2x/sec).

2022-05-16 07:12:25 ERROR (MainThread) [lennoxs30api.s30api_async] messagePump unknown SenderId/SystemId [KL21xxxxxx]

The ID at the end has been redacted. I see two distinct ID's which I assume correspond to my thermostats/systems.

Browsing through your codebase I think this is coming from the cloud API component, but I'm not using the cloud connection so not understanding why I see the error. I have the integration connecting to my thermostats locally and everything seems to be stable (with the exception of this error).

Anyone else seeing this?

**Comment by PeteRager** [comment]
That's interesting, never seen that before.

What model thermostats do you have?

Let's capture the message logs.  Go into configuration for each integration select the option to log messages to a file, give it a unique file name like "s30_message_connecition_1.log" (and a different one for the second), reload or restart the integration.  

Upload those and/or search through them.  I'd like to see both Good and Bad messages.  If the redaction is causing issues, there is an option to turn that off; if you do that, those files have personal information in it that you would not want to post.

**Comment by PeteRager** [comment]
And grab the software version running on the thermo.  That should be in the lennox30.state objects.

softwareVersion: 3.81.207

**Comment by PeteRager** [comment]
I'm pretty sure you'll need to remove the redaction by enabling the "Personal Info in log file"

Here's an example from my logfile.  The SenderID for local connections is always LCC - except in your case.  Would be good to see if some message have LCC and other have the KL21xxxx  and what the content of those KL21* messages are.

```
    "messages": [
        {
            "MessageId": 0,
            "SenderID": "**redacted**",
            "TargetID": "ha_prod",
            "MessageType": "PropertyChange",
            "Data": {
                "system": {
                    "status": {
                        "outdoorTemperatureStatus": "good",
                        "outdoorTemperature": 77,
                        "outdoorTemperatureC": 25
                    },
                    "publisher": {
                        "publisherName": "lcc"
                    }
                }
            }
        }
    ]
}
```

**Comment by PeteRager** [comment]
That is very interesting.   This a configuration I haven’t seen before.  I know one person with 2 seperate hubs but they aren’t chained together like this.  This may also explain the very high level of instability with diag level 2 as you have 2x the message volume. 

I would like the logfiles.   I have a simulator I can load them into. Email them to pete dot sage at icloud dot com

Now, we need to figure out what to do.

A) Ignore/drop the messages. The simple solution is to have each connection ignore the messages not coming from LCC if it matches something in that siblings data structure.   So instead of logging an error we would do nothing.  

B) Connect to one hub (this would be the primary). In this solution we’d  have a single connection to the one hub and get messages from primary and secondary hubs.  This is the way the cloud connection works - a single connection and data may come from multiple hubs.

The benefits of A are its simple and if one hub is disconnected data will flow from the other hub.  The disadvantage is we are doubling the network load and the load on the integration.

The benefits of B is we minimize the network load and integration load.  The disadvantage is that the change is a little more involved.  We’d also need to prove out that commands get routed correctly from the primary to the secondary hub.

Either way, we may want to also have an immediate fix to stop filling your log up with errors.

**Comment by PeteRager** [comment]
Sent you a PM with questions on the Log Files.  Once that is sorted out here's a test I'd like you to try:

Go into the integrations configuration and change the Application Id from the default "homeassistant" to a connection specific id - for example "ha_nnn" where nnn is the last three of the ip address.  The name doesn't matter, we just want them different and to be able to identify which controller it is connected to.

After making the change, reload the integration.

It is possible that the App_Id is a global identifier across the two controllers and hence all messages are getting routed to both integrations.  By making them unique, it may change this behavior and remove the error. It's also possible this changes nothing.  Either way it'd be good to know.  I saw evidence of the same messages being sent back to back more that once; which is a behavior I haven't seen before either.

**Comment by PeteRager** [comment]
As I’m looking through the configuration for your system.

There appear to be two zones in your system.  One on each S30. And hence  there are 2 climate entities in HA

Are there two furnaces and two outdoor units or one furnace and one outdoor unit?  Right now are there two working outdoor temperature sensors in HA?

**Comment by PeteRager** [comment]
For now, I've decided to take the simple approach and drop these messages.  Option (A) above.  Most of the changes for Option A are needed for Option B.  So this gets us started and if we need to go further we can.

Changes included in the pull request:

- Fix for message logger #156
- Process the sibling configuration information to capture the names, ip address of the sibling.  This only processed data for a single sibling (our current use case), if it encounters multiple siblings an error will be logged.  Include the sibling information in the diagnostic state object
- Drop messages from the sibling, log a debug message, and increment a new diagnostic state entity attribute "sibling_message_drop"
- If the message is not from a sibling, log an error message, and increment a new diagnostic state entity attribute "sender_message_drop"

Bulk of changes are on the API side:
https://github.com/PeteRager/lennoxs30api/pull/42

**Comment by PeteRager** [comment]
Updated state object with new diagnostic counters / info.
![sibling](https://user-images.githubusercontent.com/76050312/169409602-fe8d0714-4e84-4868-8769-ad84298272fe.PNG)

**Comment by ziz480** [comment]
Thank you! 

> As I’m looking through the configuration for your system.
> 
> There appear to be two zones in your system. One on each S30. And hence there are 2 climate entities in HA
> 
> Are there two furnaces and two outdoor units or one furnace and one outdoor unit? Right now are there two working outdoor temperature sensors in HA?

Yes, I have two climate entities & two outdoor temp entities in HA. Outdoor temperature seems to be reported correctly. The climate entities function and report correct temperature/target humidity as well. I basically have two complete systems (2x furnaces, 2x coils & 2x outdoor units).

**Comment by PeteRager** [comment]
Thanks for that explanation, that makes sense as an S30 can only control a single furnace, etc.  So they chained them together.

New logs you sent are perfect.

I'm a day or two away from having the updated release.

**Comment by PeteRager** [comment]
I'm merging the pull request and creating a release, that will automatically close this issue.  I will update when the release is finalized

**Comment by PeteRager** [comment]
https://github.com/PeteRager/lennoxs30/releases/tag/v0.2.7
