### ISSUE TITLE
iHarmony Zoning toggle?

### ISSUE THREAD

**Issue by smkelly** [PeteRager/lennoxs30#160]
I have a two zone Lennox system, but I don't always have iHarmony zoning activated. Mostly because it takes my variable stage system and seems to turn it into a two stage system.

Any chance there is a way to toggle iHarmony Zoning on/off via a switch entity?

**Comment by PeteRager** [comment]
Sure we should be able to do that.  First we’ll need to decipher the command.  My system does not do that, so I’ll need your help.

1. Enable message logging.   Go into integration configuration, check the “log messages to file” and enter a file name like s30_message.log.  Reload the integration or restart HA for this to take effect.
2. Once the integration is back up for a few minutes.  Enable iHarmony Zoning (note the time), wait a couple of minutes then disable it (note the time).
3. Grab the message log (should be in same folder as home assistant log)
4. Post it here (all personal information is redacted) or email it to me


In that file we should see the messages that get sent to the integration when the zoning mode is changed, as well as the complete config of your system which I’ll also need.  With that information I should be able to determine the messages to send.

**Comment by PeteRager** [comment]
Updated prior messsge

**Comment by smkelly** [comment]
I did the log capture and there is a *lot* here. I'm digging through it looking for the actual correct part. Will provide when I have it.

On zoning behavior, you are correct. When iHarmony Zoning is disabled, the entire system becomes a 1 zone system. You can no longer scroll through the zones on the S30 in Zone 1; it only shows itself. The stats *in* the other zones still show their data, but you cannot adjust heat/cool/setpoints on them. In essence, they become dumb boxes that show the current temperature. So it seems reasonable to hide the mode and setpoints on zones 2,3,4 if zoning is disabled.

Installing the integration was interesting as it showed all of this on the zones even when they are inactive. I had no idea the thermostat even had that data.

Thanks again for your help and quick response. I really appreciate all of your work here.

**Comment by smkelly** [comment]
[s30log.txt](https://github.com/PeteRager/lennoxs30/files/8767177/s30log.txt)

Attached is the captured log with (hopefully) all personal information hidden. Notes at the top on on/off time for iHarmony Zoning.

**Comment by PeteRager** [comment]
Thanks, that is perfect.  I have a simulator I can load these messages into.  

Looks like it’s that config parameter centralMode that you identified.  Should be pretty easy to get that connected to a switch.  I’ll start looking at it.

**Comment by PeteRager** [comment]
Pull request for API
https://github.com/PeteRager/lennoxs30api/pull/43

**Comment by PeteRager** [comment]
I created a project for 0.2.8 that has a set of features related to this one.  In that they are all setting elements in that configuration structure.  Anyways, probably a week or two away.

**Comment by smkelly** [comment]
Awesome. Thanks. I'm also happy to test anything. I'm qualified to apply patches, check out commits, or whatever.

Unrelated, ever since I installed this component, my flaky S30 wifi issues have vanished. The thermostat would often be unavailable in the app. I *think* this probing the S30 enough that it mitigates an undiagnosed wifi issue or something where it was going to sleep, entering a power save state, or who knows what. UniFi UAP-AC-PROs. So that is another benefit to your work. Thanks!

**Comment by PeteRager** [comment]
Sounds good.   I’ll need you to do the final test that sending the centralMode command actually works.  It should.

That  is interesting.  Their app has multiple modes of operation and the iOS versions is different than android.  One way it works is by talking to the Lennox Cloud Servers, this uses the same REST API / JSON structure that local connection use though different with/URLs.  Before we knew the URLs for local, the integration would only work with the cloud connection.   And yes, getting the config would often time out (that’s what happens when the app is black), the config are those big messages at the start of the log.   The cloud acts as a message relay, so the S30 pull requests down and send stuff out.  Lots of steps / infrastructure and opportunity for failures.  Restarting the integration was always a gamble.  Never thought it was the S30 taking a nap!   The iOS app will also connect locally if it’s on your LAN, it uses some very complicated OpenDDS protocol….

**Comment by PeteRager** [comment]
The wifi signal strength appears in the message logs.  Looks a little low?

```

                           "status": {
                                "macAddr": "**redacted**",
                                "ssid": "**redacted**",
                                "ip": "**redacted**",
                                "router": "**redacted**",
                                "networkStatus": "enabled",
                                "channel": 0,
                                "dns": "**redacted**",
                                "dns2": "",
                                "subnetMask": "**redacted**",
                                "bitRate": 58500000,
                                "speed": " 58.5 MBit per second",
                                "rssi": -73
                            },
 
```

**Comment by smkelly** [comment]
The switch is for zoning being enabled. So, on==zoned, off==central.

Off:
![image](https://user-images.githubusercontent.com/1743778/171276274-6ad8567a-f1df-4187-a43b-b2aaa2f17998.png)

On:
![image](https://user-images.githubusercontent.com/1743778/171276500-b48b2c9d-7577-451f-ac2e-50dd1515e83f.png)

Re: your observation about wifi signal... I have 3 APs in the house and it prefers to associate with the furthest one away. I had been experimenting with the UniFi controller to force it to associate with the closest one. I was *not* doing that when I captured this data, so you are seeing the wifi signal for talking to the furthest away AP.

**Comment by PeteRager** [comment]
Thanks for the detailed info and screen shot.  Got the initial code of the switch done.

**Comment by smkelly** [comment]
This throws a traceback on initialization. It does look like I'm running with the required lennoxs30api package:
```
smkelly@hass ~> docker exec hass pip3 list|grep lennox
lennoxs30api                     0.1.9
```

The traceback:
```
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 257, in _async_setup_platform
    await asyncio.gather(*pending)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 382, in async_add_entities
    await asyncio.gather(*tasks)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 619, in _async_add_entity
    await entity.add_to_platform_finish()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 810, in add_to_platform_finish
    self.async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 533, in async_write_ha_state
    self._async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 571, in _async_write_ha_state
    state = self._stringify_state(available)
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 539, in _stringify_state
    if (state := self.state) is None:
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1003, in state
    if (is_on := self.is_on) is None:
  File "/config/custom_components/lennoxs30/switch.py", line 403, in is_on
    return self._system.centralMode == False
AttributeError: 'lennox_system' object has no attribute 'centralMode'
```

This results in the switch being `unavailable` in HA.

**Comment by PeteRager** [comment]
Apologies, my note was not clear.  Code is not ready for testing yet.  Yes, to get it to run you’d need to grab the updated API. Give me a few more days and I’ll push api 0.1.10 to pypi.

**Comment by PeteRager** [comment]
Quick update, I have code complete for this an other items for the release.  Next step is testing on the simulator, then testing on a live system.  Once I get through that - another couple of days - I'll have something ready for you to test.

**Comment by smkelly** [comment]
That looks amazing! Thank you for all of the work on this.

**Comment by PeteRager** [comment]
- [ ]

**Comment by smkelly** [comment]
Testing results:

- Verify the switch is created to control the zoning Mode: Confirmed
- Verify the switch is in the correct state: Confirmed
- Test toggling the switch from the S30 Panel or the Lennox App
  - The HA switch should follow this state: Confirmed
  - The Climate Zoning Attribute should follow this state: Confirmed
  - Zones other than Zone 1 should be disabled when in "central" mode - except for current temperature/humidity: Confirmed
  - Zone 1 should always function regardless of state: Confirmed
- Test toggling the switch from HA
  - The S30 Panel should follow this state: Confirmed
  - The Climate Zoning Attribute should follow this state: Confirmed
  - Zones other than Zone 1 should be disabled when in "central" mode - except for current temperature/humidity: Confirmed
  - The physical thermostats should behave the same as they do when toggling the mode from the Lennox Panel / App: Confirmed
  - Zone 1 should always function regardless of state: Confirmed

Not only is this working perfectly, you provided some very thorough testing. This is some top notch work. Thank you so much for adding this feature. I really appreciate it and already have automations to control zoned/central for my house.

**Comment by PeteRager** [comment]
Excellent, thanks for the testing.

The unit testing (pytest) is instrumental in the quality.  There are more new lines of unit test, than code.

The API contains an S30 simulator, which aids in system testing, so for this I set it up to send the messages you had captured.

Anyways enjoy the feature, good working with you.
