### ISSUE TITLE
[Sept Release] Deprecated constants

### ISSUE THREAD

**Issue by PeteRager** [PeteRager/lennoxs30#178]
See this post

https://developers.home-assistant.io/blog/2022/05/03/constants-deprecations
https://developers.home-assistant.io/blog/2022/04/02/support-constants-deprecation

**Comment by Paulbhyo** [comment]
Hello,  i know you have this update request,   I wasn't sure if this language was in the logs for 2022.7. but 2022.8 says that you have until 2022.10 to fix it.   Or this could be a separate issue all together. 

Logger: homeassistant.components.number
Source: components/number/__init__.py:119
Integration: Number (documentation, issues)
First occurred: August 12, 2022 at 7:15:51 PM (4 occurrences)
Last logged: August 12, 2022 at 7:15:51 PM

custom_components.lennoxs30.number::DiagnosticLevelNumber is overriding deprecated methods on an instance of NumberEntity, this is not valid and will be unsupported from Home Assistant 2022.10. Please report it to the custom integration author.
custom_components.lennoxs30.number::DehumidificationOverCooling is overriding deprecated methods on an instance of NumberEntity, this is not valid and will be unsupported from Home Assistant 2022.10. Please report it to the custom integration author.
custom_components.lennoxs30.number::CirculateTime is overriding deprecated methods on an instance of NumberEntity, this is not valid and will be unsupported from Home Assistant 2022.10. Please report it to the custom integration author.
custom_components.lennoxs30.number::TimedVentilationNumber is overriding deprecated methods on an instance of NumberEntity, this is not valid and will be unsupported from Home Assistant 2022.10. Please report it to the custom integration author.
