### ISSUE TITLE
Ventilation Control

### ISSUE THREAD

**Issue by Paulbhyo** [PeteRager/lennoxs30#187]
Ventilation control using an ERV.  

Id like to have a switch that I can turn on to tell the ventilator to run for a preset / configurable time. 

I have an S30 thermostat, SPL99V furnace, XC20 AC Unit, all modulating,  the ERV ventilation is configured but we don't have it setup for any special modes,  its off most of the time.  
[S30_Local (1).log](https://github.com/PeteRager/lennoxs30/files/9226579/S30_Local.1.log)

I've uploaded the log file showing that I turned in on and off,  and on, let the time expire, then i turned in on again the last time I turned it on I set it to 1hour (1800 in the logs it looks like),  

The thermostat turns on the ventilator by going to the ventilation menu, selecting ventilate now,  select a time value and it runs for that length of time.   if you want to stop the ventilation there is a button that says stop ventilating. 

let me know if I missed something.  or if I need to try something.  I'm a Home Assistant NOOB,  but I can muddle my way around some things. 

I also need to mention that I don't use the "on" or "timed" function for the ventilation.   at some point since it was installed (Oct - 2019) it non longer operates the ventilator.  the ventilator used to run all the time if it was set to on,  then the timed mode would operate the vent at a timed interval as setup in the configuration.  now it doesn't do anything.  I need to call the installer and see if they can figure out why it doesn't work.   The only thing that turns the ventilator on is to set the ventilate now, and I know that works because I can hear the fan on the ERV kick on with that setting. 

![20220730_094957](https://user-images.githubusercontent.com/109493887/181917547-681d3ec7-b748-4ec0-a9f6-99d159c292c1.jpg)
![20220730_095004](https://user-images.githubusercontent.com/109493887/181917672-4c93d607-aecf-47b6-b669-3baaf5ce0c46.jpg)
![20220730_095010](https://user-images.githubusercontent.com/109493887/181917673-cef25bda-8960-4435-a2d9-6718bd7956c8.jpg)
![20220730_095022](https://user-images.githubusercontent.com/109493887/181917687-9369d3d6-804a-41e0-b18c-27419b073768.jpg)
this is what the main screen looks like after enabling the ventilator from the other screens. 
![20220730_094946](https://user-images.githubusercontent.com/109493887/181919682-45bd7dd1-536e-48fb-aed1-62f233be00db.jpg)

**Comment by PeteRager** [comment]
Thanks, that is great information.
This configuration indicates you have a 1 speed ERV and a 1 zone system.  Does that make sense?

```
                            "ventilation": {
                                "unitType": "1_stage_erv",
                                "controlMode": "timed"
                            },
```

The integration is currently checking that unit type for the string "ventilator".  When it detects that it creates a switch to turn the ventilator on and off.  Right now it does not support the timed mode.  I'm not sure of the command to do that yet.  Do you want timed mode from HA or is being able to turn it on / off sufficient?

The status data coming back looks different compared to where it appears in your system.  In your system there is a ventilation parameter that is part of the zone that indicates if ventilation is turned on / off.   In systems with unitType "ventilation" this appears in the system message.

```
    "messages": [
        {
            "MessageId": 0,
            "SenderID": "**redacted**",
            "TargetID": "LennoxS30",
            "MessageType": "PropertyChange",
            "Data": {
                "zones": [
                    {
                        "publisher": {
                            "publisherName": "lcc"
                        },
                        "status": {
                            "fan": false,
                            "allergenDefender": false,
                            "humidity": 49,
                            "temperature": 72,
                            "damper": 0,
                            "heatCoast": false,
                            "defrost": false,
                            "humidityStatus": "good",
                            "period": {
                                "systemMode": "cool",
                                "fanMode": "auto",
                                "husp": 35,
                                "sp": 73,
                                "desp": 50,
                                "csp": 73,
                                "hsp": 62,
                                "hspC": 16.5,
                                "startTime": 453600,
                                "humidityMode": "dehumidify",
                                "spC": 23,
                                "cspC": 23
                            },
                            "humOperation": "waiting",
                            "scheduleExceptionIds": [],
                            "balancePoint": "none",
                            "tempOperation": "off",
                            "ventilation": true,
                            "demand": 0,
                            "aux": false,
                            "coolCoast": false,
                            "ssr": false,
                            "temperatureStatus": "good",
                            "temperatureC": 22
                        },
                        "id": 0
                    }
                ]
            }
        }
    ]
}
```

If you want to do a simple test, you could manually edit switch.py on line 33.  If you don't feel confident doing that, that is OK also, and I can work on a test version.  First copy off the old switch.py to somewhere else.

```
        if system.supports_ventilation():
            _LOGGER.info(f"Create S30 ventilation switch system [{system.sysId}]")
            switch = S30VentilationSwitch(hass, manager, system)
            switch_list.append(switch)
```

add this line to hard code the unit type to ventilator

```
        system.ventilationUnitType = "ventilator"
        if system.supports_ventilation():
            _LOGGER.info(f"Create S30 ventilation switch system [{system.sysId}]")
            switch = S30VentilationSwitch(hass, manager, system)
            switch_list.append(switch)
```

when you restart HA the switch should get created.  The switch state will not track what you do in the panel without further changes, but this will allow us to determine if the existing command to turn ventilation on and off works.  So the test would be this:

1. Shutdown HA, make the edit, 
2. Have the hvac system running in a mode where turning ventilation on will actually do something, start with ventilation turned off on the panel
3. Restart HA
4. Verify the integration comes up, if is doesn't look for errors in the log, double check the change (indentation matters)
5. Find the switch entity that gets created, it should be in an Off state
6. Turn the HA switch on, see if this turns the physical ventilator on and if the S30 panel shows the right status.
7. Turn the HA switch off, see if this turns the physical ventilator back off and if the S30 panel shows the right status.

**Comment by Paulbhyo** [comment]
Hello, 

On / Off control was all I was looking for. 

I tried to turn it on and off with your method and it didn't seem to operate as I expected. So I put the old code back. 

I ended up changing the Lennox configuration to fresh air damper and the switch for on/off shows up in home assistant and it turns the ventilator switch on the thermostat always on and always off.   the switch seems to work on the thermostat,  but the ventilator doesn't work as expected.  same operation as I had before,  I think that there is something going on in my thermostat, smart hub or Lennox changed the conditions that allow the ventilator to work.  I'm half tempted to reset everything to defaults and set it back up..  but I'm not a pro and id probably break something.   

Some observations 

Setting the ventilation to a timed amount from the thermostat doesn't show on the control switch status but the status shows in the zone ; ventilation is on (true).   

The controlMode you show only has two states in the Lennox configuration.  "Ashrae" or "Timed".   Ashrae is a mode that monitors turnover in the house and some compliance to a government standard..  the Timed mode is just so many cycles or time in an hour.   Neither of which are important to me,  I just was expecting to turn the ventilation on or off.  we use it when we burn food or cook bacon.  The switch appearance (available  or unavailable) in home assistant doesn't seem to be impacted by changing this setting. 

With home assistant I can create an automation that just turns it off after some time.  This is way easier than trying to automation something that plugs in time values in the thermostat.    Ill still need to reach out to Lennox to see why its not working.

**Comment by PeteRager** [comment]
Thanks for running. The test. Let me make sure I understand.

1.  With the temporary change and equipment set to 1 speed  ERV.  Turning the switch on had no effect on the ERV and the S30 Panel.
2. With the released code and and equipment set to “Fresh Air Damper”.  The switch got created and turning the switch on was reflected in the S30, but the ERV did not turn on.
3. “Setting the ventilation to a timed amount from the thermostat doesn't show on the control switch status but the status shows in the zone ; ventilation is on (true).”  This was with released code and equipment set to “Fresh Air Damper” and the climate zone ventilation attribute shows True but the switch is off.4. 
4. The only way your ERV will turn on is if it’s in 1 speed ERV and you press the ventilate now button?

The switch does have an attribute that shows the remaining time.  Based on your log that attribute should be working.

A multimeter on ACC1 should show presence / no presences of 24vac?

**Comment by Paulbhyo** [comment]
I had chance to play with this some more and verify your questions.  I used program industrial equipment, and not conveying factual information can lead you down a rabbit hole. 

1. I re-tried the code and put the thermostat back to 1 speed ERV.  this does work, I must have done something incorrectly before.  HA is able to turn the status on and off and that is reflected in thermostat. the checkmark moves to always on or always off based on the switch state in HA. 
2. with it sent to "Fresh Air Damper" I didn't need the code to force the switch to appear.   HA is able to turn the status on and off and that is reflected in thermostat. the checkmark moves to always on or always off based on the switch state in HA. 
3. when using the ventilate now button and setting a time,  this turns the ACC1 relay on reliably, and the status says ventilation true under zone1,  however the HA switch follows the state of the Always On/Off  on the thermostat.  so if the stat is Always off, HA stays off.  I don't think this is a problem. 
4. It seemed that way.  however its seems to be random, since i can turn it on from home assistant it does turn on randomly, trying to figure out what is keeping it off.  every time the ACC1 is on and the ventilator is truly running it shows correctly in HA for the zone status. 

I have 24V at the smart hub,  the ventilator does work,  its just something on the lennox side that makes it random with the always on setting. it doesn't follow fan operation or cooling mode.

**Comment by PeteRager** [comment]
Thanks.  Very helpful.

Here is a proposed set of changes for review.

Change 1 - the switch should be created when ventilation is in “Damper”, “1 speed ERV”, or “1 speed HRV”, log warnings for unsupported ventilation types (2 speed) with a link to Change 3.  Update the documentation to describe this as Always On / Always Off and not supporting timed ventilation. 

Change 2 -  Timed ventilation reporting .  The current state is the switch attribute has the remaining ventilation time and the zone climate entity has the ventilation status.  So if I add the ventilation remaining time to the climate entity then all the info is in one place - which is an improvement. 

These next items are for the backlog.  

Change 3 - If it’s a two speed ERV or HRV we’d need a select entity that allows setting it to off, low, high.  This I’ll put on the issue backlog and address when someone needs it.

Change 4 - Timed ventilation control.  This would allow setting a timed ventilation and cancelling it.  There is some work to determine what message to send.

Does that cover it?

**Comment by Paulbhyo** [comment]
Yes. sounds pretty thorough.   

I'm not sure how useful change 4 would be to the average home assistant user. If I need to have it on for a configurable time, it could be done with automation pretty easy.   I could see a scenario where it might be desirable to return the ventilation to the "Timed" or "Ashrae" mode vs on and off.   I suspect its a matter of sending it a different string kind of like how the zone schedule setting is setup,  its a drop down list of available modes.  just a thought anyway. 

Thanks for all of your help.

**Comment by PeteRager** [comment]
Thanks.  I did some local testing this morning on my single zone AC system.  Since the ventilation interface isn't via their communicating RSBus and it just toggles ACC1 and/or ACC2, it let me set it up, even though I have no equipment attached.

Couple of discoveries.
- For 2 Speed ERV and 2 Speed HRV - it works the same as a 1 speed ERV.  The only option you have is to turn it on.  The high and low modes are selected by the controller based on the configuration parameters (temperature thresholds, etc.).  So this is good news, from the integrations perspective all of these work the same and I can cover them all from item 2.  Fundamentally, the difference is the control algorithm used by the S30.

- On timed mode, I agree it's not super useful.  However, since I was already detailing this, I wanted to take the extra minutes and determine how it works.  It's actually very simple:

To turn on for 10 minutes

```
                "Data":
                {
                    "systemController":
                     { 
                        "command":"ventilateNow 600"
                     }
                }
```

and to turn timed mode off

```
                "Data":
                {
                    "systemController":
                     { 
                        "command":"ventilateNow 0"
                     }
                }
```

Not exactly sure what I'm going to do with this information yet.

I'll start working on the changes and keep you updated here.  Typically takes about a week or so to get an update out.

I may also create a new device for the ventilation equipment and move the switch there.

**Comment by PeteRager** [comment]
On the timed ventilation.  Here is what I’m going to do.

1.  Create a number entity that holds the requested duration in seconds
2. When the existing switch is turned on:
  - if the duration is zero, it will do an always on
  - If the duration is non zero, it will do a timed on for that duration
3. When the existing switch is turned off:
  - if there is a timed duration active, it will cancel it
  - If the always on is on it will cancel it.
4. The switch state will be on when either always on is on, or there is an active timed ventilation
5. The switch state will be off when always on is off and there is no active timed ventilation
6. I will keep the remaining duration as an attribute of the switch.
7. I will add attribute(s) to the switch to discern the on state (always on vs timed)

so for example, if you want an automation to turn it on for 60 minutes:
1. Set the number entity to 3600
2. set the switch to on

with the added benefit of being able to cancel it by turning the switch off.

**Comment by PeteRager** [comment]
Linking the initial pull request.  Pull request is not ready for testing.

**Comment by PeteRager** [comment]
Quick update.  I've pulled a couple other bug fixes into the release, they are now code and unit tested.  Next steps are to perform functional testing and then package the release.  Should be done next week.

**Comment by PeteRager** [comment]
Was autoclosed well pull request was merged.  Release will be available in a day or so.  Will post here when ready.

**Comment by PeteRager** [comment]
Release is out. Thanks for your help on this item.   Give it a try when you have some time.

https://github.com/PeteRager/lennoxs30/releases/tag/0.2.12
