### ISSUE TITLE
Port to Hubitat

### ISSUE THREAD

**Issue by rumym** [PeteRager/lennoxs30#191]
Hi there, there seems to be a fair bit of interest in using this on Hubitat. Would you be interested in porting this to hubitat?

https://community.hubitat.com/t/integration-with-lennox-icomfort-s30-thermostat/49849/15

**Comment by PeteRager** [comment]
Don’t know much about hubitat and how to do that.  Are there docs?

There are two pieces, the HA integration and the API (https://github.com/PeteRager/lennoxs30api).  So to create a hubitat integration starting with the API, would be an approach.

The other approach could be to build an MQTT component and then any product that support MQTT could work.
