### ISSUE TITLE
Schedule Hold

### ISSUE THREAD

**Issue by mcfarlde** [PeteRager/lennoxs30#195]
When I use this integration with my S30, it sets schedule hold state.  I can cancel hold to get back to how the thermostat is supposed to operate but then schedule hold is initiated again at the next schedule change I think.   It is like the integration is setting a value different than the schedule at transition which triggers the hold.

**Comment by PeteRager** [comment]
That is interesting.   The integration does not send commands to the thermostat on its own, it only sends commands when requested to by an automation or from a Lovelace card.  There are several possibilities:

1. There are automations configured that ran and changed something 
2. The thermostat was adjusted by someone - from the panel, HA or mobile app
3. Something is broken

Does this situation reliably reoccur? Or was this a one off?

if it reproduces, then I’d suggest capturing a full debug log as that’ll show the messages going back and forth as well as the integration adding and removing holds.

Instructions are here.

https://github.com/PeteRager/lennoxs30#reporting-bugs

I’ll need both the home assistant log file and the message log file.

**Comment by mcfarlde** [comment]
Hello,

I also suspected tampering or an app on a phone.  I disabled all including the HA integration and the S30 works as expected.  Enabling the integration only brought the problem back.  I am confident I have not made any automations referencing the integration but will look again soon.  I really only notice because of the schedule hold text on the S30 and the fact the fan does not follow its scheduled setting of On when in schedule hold mode.  The temperature settings are following the S30 schedule.  I have no apps connected but have noticed a widget on my iPhone.  I don’t know where it came from and will try to remove it.

Cheers

**Comment by PeteRager** [comment]
Ok, I'd go about capturing those debug logs then.

I do believe that the Fan setting is not part of the schedule.  When I first got my S30, i wanted to be able to schedule the fan to coming on as part of schedule and then go off on a different part of the schedule.  This was not possible, hence I started creating this integration so I could do that.

Anyways, getting the logs will be the next step.   You can post here or email to me.

**Comment by PeteRager** [comment]
Closing the stale issue, please reopen if needed
