### ISSUE TITLE
S30 no longer detected because of ip address change

### ISSUE THREAD

**Issue by rugene76** [PeteRager/lennoxs30#206]
For some reason the ip address of my s30 changed on me. (from 10.0.0.177 to 10.0.0.178)
So now my s30 is no longer detected by the integration. How do I force the integration to rediscover the IP of the S30?
thanks

HA error log below (the s30 is now 10.0.0.178):
Logger: custom_components.lennoxs30
Source: custom_components/lennoxs30/__init__.py:610
Integration: Lennox S30/E30 ([documentation](https://github.com/PeteRager/lennoxs30/blob/master/README.MD), [issues](https://github.com/PeteRager/lennoxs30/issues))
First occurred: 10:00:21 AM (7 occurrences)
Last logged: 10:06:39 AM

async_setup host [10.0.0.177] unexpected error Code [11] Reference [400] [login Client Connector Error - failed due host not reachable url [https://10.0.0.177/Endpoints/ha_prod/Connect]Message ConnectionKey(host='10.0.0.177', port=443, is_ssl=True, ssl=<ssl.SSLContext object at 0x7f908928c0>, proxy=None, proxy_auth=None, proxy_headers_hash=None)Message [Errno 113] Connect call failed ('10.0.0.177', 443)]

**Comment by PeteRager** [comment]
To prevent the IP address from changing, setup a “dhcp static lease” in your router.   This essentially provides a permanent IP address for the S30 that will never change.  Without this it will change again in the future.  The specifics of how to do this are router dependent.  Look at the routers docs and/or send me a link.

https://github.com/PeteRager/lennoxs30#requirements

The best recovery will be to set up the static lease to give the S30 its old IP address 10.0.0.177.  After setting up the new lease power cycle or reboot the router, when the S30 reconnects it should get its old IP address and then the integration will reconnect.

There are two alternative work arounds, however, the when the IP address changes again in the future, the same problems will occur.  Hence, the best and recommended approach is to assign the static IP address.

An alternative is to edit the .storage/config_entries file and change the IP address of the integration.  You’ll want to change it in the ip_address field as well as the name.  Home Assistant should be shutdown before you edit this file and then restarted once the file is edited.  Be careful and make a backup, as a syntax error in this file may cause HASS to fail to start.

The third option is to delete the integration, restart HASS, then add it back in,  However if you have customized the friendly names, entity ids, etc., all that info will be lost.

**Comment by PeteRager** [comment]
Sounds good. Yeah, discovery would be helpful.  I’m sure there’s a way… and Yes, it’s a lot of work managing IP addresses…. I have mine at a static address and then have a firewall around it - to prevent it talking out and to only allow HASS (and my dev computer) to talk to it.
