### ISSUE TITLE
Permanent Connect Errors started occurring on a system was stable

### ISSUE THREAD

**Issue by PeteRager** [PeteRager/lennoxs30#209]
**Describe the bug**
This is a bug with the Lennox S30.

I have a Lennox S30 system with diags enabled using parameters beta to control fan CFM.  While I was away, the integration lost connection to the S30 using the local LAN connection.  I was able to ping the S30, remotely rebooted the WIFI router and Firewall which did not fix the situation.  I was able to telnet into port 443. I disabled the firewall rules that prevent it from talking to Lennox cloud and was able to then use the IOS app to connect and see that the system was indeed working.  When I got home, I went to the thermostat panel and selected restart hub + thermostat.  Once the system rebooted, the integration reconnected.  The conclusion is that the daemon the responds to traffic on 443 must have be hung or crashed.

**To Reproduce**
Only happened once, I’ve been using local connections for over a year

**Expected behavior**

**Screenshots/Logs**

**Version**
 - Home Assistant: 2022.8.06
 - This Integration: 2022.9.0
 

**Integration Configuration **
- Cloud or Local Connection: Local
- Inverter or Sensor Diagnostics Enabled: Yes

**Additional context**

**Comment by PeteRager** [comment]
If other encounter this it’d be good to know.

I will work to add a command to trigger a reboot of the S30.  While this wouldn’t have worked on the local connection, I’m pretty sure the command could have routed through a cloud connection and remotely rebooted the S30 and solved this problem without requiring physical access to the device.  

I may also look at putting a relay in (zwave) so I can cut the power to the S30.

**Comment by owenfi** [comment]
Is this the instability with leaving the internet connection up, or is this independent/in -addition? I finally got my SLP99 install mostly up and running (plan to add zoning soon) and am super eager to try out this integration!

**Comment by PeteRager** [comment]
Good question.  The occurred on a system that was firewalled off from the internet.  It’s only happened once.

The symptoms of the internet instability when diagnostics are enabled include:
 - frequent controller reboots
 - Continuous communication errors
 
That said, there are people using diagnostics with the S30 internet connected successfully.  Lennox does rev the firmware, so it is possible they have resolved some of these issues.  Their controller does upload error logs.

**Comment by PeteRager** [comment]
Automatic close due to inactivity
