### ISSUE TITLE
[HASS Deprecation] is_metric deprecated property - 2023.1.0

### ISSUE THREAD

**Issue by bstempien** [PeteRager/lennoxs30#214]
Installed 2022.11.5 today and noticed this in my Logs.

Detected integration that accesses the `is_metric` property of the unit system. This is deprecated and will stop working in Home Assistant 2023.1. Please adjust to use instance check instead.. Please report issue to the custom integration author for lennoxs30 using this method at custom_components/lennoxs30/__init__.py, line 435: self._is_metric: bool = hass.config.units.is_metric**Describe the bug**

**Comment by PeteRager** [comment]
Excellent, thanks for the report.  Looks like I have 27 days to fix.

**Comment by PeteRager** [comment]
Example of the fix
https://github.com/ReneNulschDE/mbapi2020/commit/7e97db780c3fad13c5fbd99d2e6b177d873a4291

**Comment by PeteRager** [comment]
Looks like this change was introduced in 2022.11.0.
