### ISSUE TITLE
I just updated Home Assistant to the Latest version, and now my Lennox integration doesn't work. 

### ISSUE THREAD

**Issue by kkolkebeck** [PeteRager/lennoxs30#229]
Any help would be appreciated. I generally don't update until the release has been out there for a few weeks. I've not had problems in the past. I reloaded both HAS and your integration. From the log, it seems like it is an issue with units of measure. 

I updated to - 
Home Assistant 2023.4.5
Supervisor 2023.04.0
Operating System 10.0
Frontend 20230411.1 - latest

Here is the log entry-
Logger: homeassistant.config_entries
Source: custom_components/lennoxs30/__init__.py:415
Integration: Lennox S30/E30 ([documentation](https://github.com/PeteRager/lennoxs30/blob/master/README.MD), [issues](https://github.com/PeteRager/lennoxs30/issues))
First occurred: 2:24:28 PM (4 occurrences)
Last logged: 4:28:09 PM

Error setting up entry 192.168.1.223 for lennoxs30
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 383, in async_setup
    result = await component.async_setup_entry(hass, self)
  File "/config/custom_components/lennoxs30/__init__.py", line 289, in async_setup_entry
    manager = Manager(
  File "/config/custom_components/lennoxs30/__init__.py", line 415, in __init__
    self._is_metric: bool = hass.config.units.is_metric
AttributeError: 'UnitSystem' object has no attribute 'is_metric'

**Comment by PeteRager** [comment]
Yep, that looks like a problem.  

The quick fix is to go into that file and change the line

```
self._is_metric: bool = hass.config.units.is_metric
```

```
self._is_metric: bool = False
```

assuming you are using Fahrenheit, otherwise set it to True

**Comment by PeteRager** [comment]
Hold on for a minute before doing that.

**Comment by PeteRager** [comment]
You are on and old version of the integration.  Upgrade to the latest which is 2023.1.0 and that issue is already fixed.

**Comment by kkolkebeck** [comment]
Ok. Thank you. KenOn Apr 19, 2023, at 6:33 PM, PeteRager ***@***.***> wrote:﻿
You are on and old version of the integration.  Upgrade to the latest which is 2023.1.0 and that issue is already fixed.

**Comment by kkolkebeck** [comment]
All fixed. Thanks for the support and love the app. I never use the Lennox app anymore. 

Ken Kolkebeck

**Comment by PeteRager** [comment]
Glad you are back up and running.  Not much worse than doing a HASS update and not getting stuff back up.
