### ISSUE TITLE
Diagnostic values show Unavailable, working before

### ISSUE THREAD

**Issue by klingon888** [PeteRager/lennoxs30#236]
I have a SLP98 furnace and XP21 HP with S30 tstat. I just migrated to a new server and restored my HASS backup. Now some of my diagnostic values are showing as Unavailable when it used to show values. I checked the S30 Diagnostics tab and all the values are shown. I've uninstalled and reinstalled the integration, still same. Any help in diagnosing this? Thanks.

![image](https://user-images.githubusercontent.com/30375535/236195725-48d3bd14-8996-4dad-bf28-178953987822.png)

**Version**
 - Home Assistant: HAASIO 2023.5.0
 - This Integration: 2023.4.0. 
 
**Integration Configuration **
- Local Connection
- Sensor Diagnostics Enabled: yes
- System_diagnostic_level: 2

**Comment by PeteRager** [comment]
I'd try toggling the diagnostic level to zero and then reset to two and see if that makes the values come available.

**Comment by klingon888** [comment]
I think 2023.5.0 broke the integration. I went back to the old server, started HASS which was on 2023.4.0 and everything worked. I then upgraded HASS to 2023.5.0 and the Unavailable started showing up. Even tried toggling Diag level, still same.

**Comment by PeteRager** [comment]
Ok, that indicates that the integration is no longer providing an entity for that value.

Go into devices and click on the device and see what entities are there.  Also, go into the entities tab and look around. There may be entities with an _2 - meaning we have dups. This could have occurred when removing and readding the integration.  

There are 3 possibilities:
a) the S30 are no longer providing these diagnostic values 
b) the entity names have changed
c) the integration is failing to create them

I'll go run a quick test on 2022.5.0 and see if it works for me.

**Comment by klingon888** [comment]
As far as I can see, no dupes. And all the entities are listed under Devices. All the Unavailable entities have this under the Status column. Clicking on it brings back the "entity is no longer provided by integration" screen
![image](https://user-images.githubusercontent.com/30375535/236214837-9c03e8ff-5b4d-41ca-b40f-807fb389f42e.png)

**Comment by PeteRager** [comment]
Would it be accurate to say that the ones that are unavailable usually do not have a numeric value?

**Comment by klingon888** [comment]
I think you're onto something with those error msgs. And your assumption is correct. Those values are typically on/off

**Comment by klingon888** [comment]
Previous working shot:
![image](https://user-images.githubusercontent.com/30375535/236217750-10b13115-c6e6-4b41-8060-92879a22ce8c.png)

**Comment by PeteRager** [comment]
Looks like a wide-spread problem, seeing many issues being reported with different integrations.
However, the integration should not be classifying an On/Off values as a measurement.  I'll start looking at a fix.

**Comment by PeteRager** [comment]
Will have new release in a few, doing installation testing

**Comment by PeteRager** [comment]
This release should fix the problem. Please verify when you have time.

https://github.com/PeteRager/lennoxs30/releases/tag/2023.5.0

**Comment by PeteRager** [comment]
Thanks for reporting it.
