### ISSUE TITLE
Disconnect call can hang thermostat

### ISSUE THREAD

**Issue by PeteRager** [PeteRager/lennoxs30#246]
Here's the raw data from PostMan for a connect, disconnect, connect sequence using the same AppID:

POST https://192.168.50.205/Endpoints/Arzel/Connect
204
82 ms
Warning: Self signed certificate
POST /Endpoints/Arzel/Connect HTTP/1.1
User-Agent: PostmanRuntime/7.32.3

HTTP/1.1 204 No Content
Server: MicroRelayServer-LCC
Connection: Keep-Alive
Content-Type: text/plain
z-conn_id: 0xb1e47484
z-method: POST
z-uri: /Endpoints/Arzel/Connect
z-time: Jun 21 16:52:41
Content-Length: 0

POST https://192.168.50.205/Endpoints/Arzel/Disconnect
204
94 ms
Warning: Self signed certificate
POST /Endpoints/Arzel/Disconnect HTTP/1.1
User-Agent: PostmanRuntime/7.32.3
Accept: /
Accept-Encoding: gzip, deflate, br
Content-Length: 0

HTTP/1.1 204 No Content
Server: MicroRelayServer-LCC
Connection: Keep-Alive
Content-Type: text/plain
z-conn_id: 0xb1e47404
z-method: POST
z-uri: /Endpoints/Arzel/Disconnect
z-time: Jun 21 16:53:01
Content-Length: 0

POST https://192.168.50.205/Endpoints/Arzel/Connect
400
68 ms
Warning: Self signed certificate
POST /Endpoints/Arzel/Connect HTTP/1.1
User-Agent: PostmanRuntime/7.32.3

HTTP/1.1 400 Bad Request
Server: MicroRelayServer-LCC
Connection: Keep-Alive
Content-Type: text/plain
Content-Length: 84
Transfer-Encoding: chunked

{"code":4,"message":"Connect Failed!: Tstat is already connected with other mobile"}

Trying any other connect with any other appID fails with the same message as above. Any subsequent disconnects result in an response that isn't even HTTP :(

POST https://192.168.50.205/Endpoints/Arzel/Disconnect
Error: Parse Error: Expected HTTP/
Request Headers
User-Agent: PostmanRuntime/7.32.3
Accept: /
Accept-Encoding: gzip, deflate, br
Content-Length: 0

**Comment by PeteRager** [comment]
I will try this on my S30 tomorrow to see if it behaves the same.

A difference between the sequence you are doing and the sequence that the integration does, is after the Connect call it establishes a subscription.  It is possible that Disconnecting from a Connection without a subscription causes some type of crash in lennox.

This endpoint should be used to establish a subscription:

POST https://{self.ip}/Messages/RequestData

With a message body similar to this.  SenderID should be your app_id "Arzel"

```
{
    "MessageType": "RequestData",
    "SenderID": "**redacted**",
    "MessageID": "3f30d00b-3282-4d31-9d6c-5bec3e564848",
    "TargetID": "LCC",
    "AdditionalParameters": {
        "JSONPath": "1;/systemControl;/systemController;/reminderSensors;/reminders;/alerts/active;/alerts/meta;/bleProvisionDB;/ble;/indoorAirQuality;/fwm;/rgw;/devices;/zones;/equipments;/schedules;/occupancy;/system"
    }
}
```

And then again

```
{
    "MessageType": "RequestData",
    "SenderID": "**redacted**",
    "MessageID": "1b8fdc51-cc67-4df9-acf7-5aeb8a9bea1e",
    "TargetID": "LCC",
    "AdditionalParameters": {
        "JSONPath": "1;/automatedTest;/zoneTestControl;/homes;/reminders;/algorithm;/historyReportFileDetails;/interfaces;/logs"
    }
}
```

From there get on this

https://{self.ip}/Messages/{self._applicationid}/Retrieve

To get messages, there will be alot of them.

**Comment by GabeDeBacker** [comment]
Tried exactly that sequence and when no more messages were retrievable, (204 response with no content), I issued a disconnect. Which succeeded. But then any further attempts to connect (or disconnect) fail and I have to restart the S40.

**Comment by PeteRager** [comment]
Interesting.  I would expect every user of this integration to run into that problem when they shutdown and restart HASS. My understanding is you are not using the integration and so have not experienced that issue with Home Assistant?

One other thing to try is to make the app_id all lower-case.  Lennox usually constructs some like dca_nnnnn from the mobile app when performing a direct connect.

**Comment by PeteRager** [comment]
I just tested this on my S30  using postman to  POST the connect and disconnect using the app_id = ha_test1 and it works fine.

I did get a weird error on Disconnect when I tried to use a Get instead of Post

**Comment by mnarusiewicz** [comment]
> Interesting. I would expect every user of this integration to run into that problem when they shutdown and restart HASS. My understanding is you are not using the integration and so have not experienced that issue with Home Assistant?
> 
> One other thing to try is to make the app_id all lower-case. Lennox usually constructs some like dca_nnnnn from the mobile app when performing a direct connect.

The integration was working fine for me with my S40's until the last Lennox firmware update which I received June 8th.  Since then it has not worked unless I restart the thermostats.

**Comment by PeteRager** [comment]
Very interesting.  And it stops working whenever you re-start the integration?  On restart is does issue the disconnect which @GabeDeBacker says created an issue.

**Comment by mnarusiewicz** [comment]
I had removed the thermostats from HA thinking it was something with an HA update or something else.  In attempting to add them I can only get to the initial integration page after a fresh reboot of the thermostats.  After they have been added to integration and reboot the thermostat again, it will show devices it found on the thermostat.

First thermostat reboot
<img width="1198" alt="Screenshot 2023-06-22 at 2 53 33 PM" src="https://github.com/PeteRager/lennoxs30/assets/25290105/acee1a5e-d63f-4cbc-b6a4-3fc3f22d22a4">

Second thermostat reboot - upstairs only (*.10 IP)
<img width="1164" alt="Screenshot 2023-06-22 at 2 58 51 PM" src="https://github.com/PeteRager/lennoxs30/assets/25290105/8e5e2389-0f34-42d1-b70d-68ab91f6b643">

**Comment by PeteRager** [comment]
That makes sense, during integration configuration it creates a connection, grabs some info and then Disconnects.

I have a patch for the API for you to test, give me 15 minutes.

**Comment by PeteRager** [comment]
I pushed a new version of the API 0.2.8

You'll need to be on the latest release of the integration which is 2023.5.2

In the custom_components/lennoxs30 directory there is a manifest.json file, edit it

replace
```
  "requirements": ["lennoxs30api==0.2.7"],
```

with

```
  "requirements": ["lennoxs30api==0.2.8"],
```

Then you will need to restart HASS and it will download the updated API.  The API should no longer issue the disconnect to an S40.

It will log a debug message:

                _LOGGER.debug("Skipping logout for S40 thermostat")

To see that you'd need to enable debug logging described here:

https://github.com/PeteRager/lennoxs30#reporting-bugs

```
logger:
  default: warning
  logs:
    custom_components.lennoxs30: debug
    lennoxs30api: debug
```

But, I'd say try the update and if the issues goes away - fantastic - if not then let's enable debug to make sure its hitting that line.

**Comment by PeteRager** [comment]
Thanks

Try to reload the integration.  That should push it through the Disconnect / Reconnect cycle.

**Comment by PeteRager** [comment]
I've verified you are running 04.20.007 same version reported in this issue #245

**Comment by mnarusiewicz** [comment]
I reloaded both thermostats.  All seems to be working as expected.  Thank you very much for resolving this so quickly.

[home-assistant.log](https://github.com/PeteRager/lennoxs30/files/11840748/home-assistant.log)

**Comment by PeteRager** [comment]
Thanks for providing the logs and reproduction scenario.  

Big call out to @GabeDeBacker for discovering and reporting the error with disconnect.  We'd still be hunting for the bug Lennox introduced. 

I'll get this packaged into a new release in the morning, the only change will be the manifest that you already updated.

**Comment by PeteRager** [comment]
Log entries verify the disconnect is being ignored for S40.

2023-06-22 17:05:11.395 INFO (MainThread) [lennoxs30api.s30api_async] logout - Entering - [https://172.16.0.9/Endpoints/homeassistant/Disconnect]
2023-06-22 17:05:11.395 DEBUG (MainThread) [lennoxs30api.s30api_async] Skipping logout for S40 thermostat
2023-06-22 17:05:11.395 DEBUG (MainThread) [lennoxs30api.s30api_async] Closing Session
2023-06-22 17:05:11.399 DEBUG (MainThread) [custom_components.lennoxs30] async_shutdown complete [172.16.0.9]


```
```

**Comment by PeteRager** [comment]
Closing this as the new release should resolve.  Open new issues if this is not the case:

https://github.com/PeteRager/lennoxs30/releases/tag/2023.6.1
