### ISSUE TITLE
Still seeing connection issues with the S40

### ISSUE THREAD

**Issue by sailorgallifrey** [PeteRager/lennoxs30#248]
**Describe the bug**
Similar to #246 I am getting the following error when trying to connect to my S40 thermostat which is on firmware version 4.20.0107.

**To Reproduce**
Steps to reproduce the behavior: Try to connect locally to S40 thermostat

**Expected behavior**
Connection is set up and temp data starts to flow

**Screenshots/Logs**
async_setup host [192.168.12.42] unexpected error Code [11] Reference [100] [login failed due to client response error [https://192.168.12.42/Endpoints/homeassistant/Connect] ClientResponseError Error while executing request: [Content-Length can't be present with Transfer-Encoding]: error=<class 'aiohttp.client_exceptions.ClientResponseError'>, resp.status=[400], resp.request_info=[RequestInfo(url=URL('https://192.168.12.42/Endpoints/homeassistant/Connect'), method='POST', headers=<CIMultiDictProxy('Host': '192.168.12.42', 'Accept': '*/*', 'Accept-Encoding': 'gzip, deflate', 'User-Agent': 'Python/3.11 aiohttp/3.8.4', 'Content-Length': '0', 'Content-Type': 'application/octet-stream')>, real_url=URL('https://192.168.12.42/Endpoints/homeassistant/Connect'))], resp.headers=[None]]
**Version**
 - Home Assistant: 2023.6.3
 - This Integration: 2023.6.1
 

**Integration Configuration **
- Cloud or Local Connection: Local
- Inverter or Sensor Diagnostics Enabled: False

**Additional context**

**Comment by sailorgallifrey** [comment]
Okay so if I connect, then reboot both home assistant and the lennox thermostat it seems to be picking up on sensors now. I still see errors in the logs periodically and it seems data isn't always coming in.

**Comment by PeteRager** [comment]
What are the errors being seen in the log.  I'd suggest enabling message logging as described in the readme.  Are you using the Lennox app on your phone?  I ask because I'm pretty sure it does this Disconnect call also and could be fouling stuff up.

**Comment by sailorgallifrey** [comment]
It was the same error I posted. It got logged a couple times, but it seems to have stabilized now. I am using the phone app so maybe that contributed. As everything is working I'm going to go ahead and close this for now.

**Comment by insertdead** [comment]
I'm still seeing the same issue with my S40 even after following the recommended steps. Maybe it's because it wasn't set up previously but on firmware 4.20.0107 I still get the error.

**Comment by PeteRager** [comment]
I'd check to make sure you are running the correct version of the integration.  Take a look at custom_components/lennoxs30/manifest.json - what do you see in it?
