### ISSUE TITLE
sensor.home_iu_indoor_blower_rpm invalid device_class

### ISSUE THREAD

**Issue by PeteRager** [PeteRager/lennoxs30#249]
**Describe the bug**
In HASS developer tools / statistics I see this message "The state class '' of this entity is not supported.", so we must be returning an empty string for the device class rather than none

**To Reproduce**

**Expected behavior**

**Screenshots/Logs**

**Version**
 - Home Assistant: 2023.5.7
 - This Integration: 2023.6.1
 

**Integration Configuration **
- Cloud or Local Connection: local
- Inverter or Sensor Diagnostics Enabled: yes

**Additional context**

**Comment by klkohl** [comment]
Is this why the blower history doesn't show a line graph?

My history shows this:

![Capture](https://github.com/PeteRager/lennoxs30/assets/88909821/ac62786a-033a-414f-8c55-cca118da1b4c)

**Comment by PeteRager** [comment]
Yes, that is an aspect of the issue. 

As a temporary workaround you can customize the entity and give it a unit_of_measurement, once you do that and restart HASS it will chart it as a line graph.

https://www.home-assistant.io/docs/configuration/customizing-devices/

**Comment by klkohl** [comment]
I looked, but can't find where the entity is defined to customize it. Can tell me where I can find it?

**Comment by 42Network** [comment]
I got this temporary workaround to work by adding these lines into my configuration.yaml file. A few things to note:

1. The "customize:" section must be under the homeassistant: line and indented 2 spaces to show it is a child node of homeassistant.
2. My thermostat is name is "s40" hence my sensor is called "s40_iu_indoor_blower_rpm". Replace the "s40" in the entity name with your actual thermostat name in HA.

```
homeassistant:
  
  customize:
    sensor.s40_iu_indoor_blower_rpm:
      unit_of_measurement: rpm
```

**Comment by klkohl** [comment]
Thanks. That works. I had created a template sensor, but I like this solution better.

**Comment by PeteRager** [comment]
https://github.com/PeteRager/lennoxs30/releases/tag/2023.10.0
