### ISSUE TITLE
SSR Meaning

### ISSUE THREAD

**Issue by aesculus** [PeteRager/lennoxs30#254]
From the installation manual:

Smooth Setback Recovery (SSR)

When enabled, smooth set back begins recovery up to two hours before the programmed time so that the programmed temperature is reached at the corresponding
programmed event time. Assume 12°F (6.72°C) per hour for first-stage gas/electric heating and 6°F (3.36°C) per hour for first-stage compressor based heating or cooling.
With Smooth Set Back disabled, the system will start a recovery at the programmed time. Options are enabled or disabled. Default is enabled.

Rules for SSR:
• SSR is enabled when both “Smooth Setback Recovery” is set to enabled (default) and the program schedule is turned on.
• SSR does NOT turn off stage delay timers.
• SSR will NOT change the dead band between heating and cooling modes.
• SSR will not overshoot the target set point.
• SSR will reset if the user updates the program schedule during the active SSR period

**Comment by PeteRager** [comment]
https://github.com/PeteRager/lennoxs30/releases/tag/2023.10.0
