### ISSUE TITLE
S40 docs for procedure to reset

### ISSUE THREAD

**Issue by PeteRager** [PeteRager/lennoxs30#256]
S40s have issues being connected to.  Add docs to the readme and enhance the error reporting to link to the resolution.

**Comment by k4j8** [comment]
Thanks for creating this amazing tool. I have been having connection issues to my S40 every few days, but usually a restart of the S40 fixes it.

Happy to help troubleshoot.

**Comment by PeteRager** [comment]
update readme

https://github.com/PeteRager/lennoxs30/releases/tag/2023.10.0
