### ISSUE TITLE
Update frequency on M30

### ISSUE THREAD

**Issue by mikepparks** [PeteRager/lennoxs30#277]
Is there a way to set the update frequency for cloud-only devices?  I'm currently running a new M30 through its paces and noticed that the states of various entities aren't being updated to reflect the current device status.  The only way I was able to get the current temperature to update, for example, was to reload the integration, but that's not sustainable for normal operations. In my current test, the temperature has dropped 5 degrees since my last reload, but is only showing the initial temperature over an hour old.

**Comment by mikepparks** [comment]
From the looks of things after some additional testing, the state of the UI is not being updated, or at least appears to be updating to values from the initial state after restart.  If I change a mode or setpoint manually on the device, those changes aren't being reflected in the UI. If I change them in the app, the proper commands are issued, but the state itself resets in HA. 

Example: If I change mode from Auto to Circulate, I hear the device switch and it displays the Circulate mode. However, the UI resets back to Auto.

**Comment by PeteRager** [comment]
Let's grab that message log, that will tell us if the changes are being received from the cloud or not.

Do other integrations update properly in HA?  Does refreshing the browser cause it to update?

**Comment by mikepparks** [comment]
Everything works in HA otherwise. Refreshing the browser does nothing to the output. Where should I send the logs?

![lennoxm30_reset](https://github.com/PeteRager/lennoxs30/assets/1214033/851e1953-25b2-40b3-8bcc-7b3a0328f028)

**Comment by PeteRager** [comment]
Pete dot sage at iCloud dot com

**Comment by PeteRager** [comment]
I got the log.  It looks like your app_id is set to your email address?  I would change it back to the default value

mapp079372367644467046827001

Restart and see if that fixes the problem.  If not try varying the last 3 digits.

**Comment by mikepparks** [comment]
Recreate it with the default app ID and it did the trick. There's a note in the "Important Information" section of the readme that could use some clarification regarding app_id values. I just noticed the note in the "Detailed Configuration Parameters" section that explains the "mapp" app_id value a bit more in detail, but it might also be worth pointing out early in the config. We can call this one good. Thanks for helping me troubleshoot that one.

**Comment by PeteRager** [comment]
Glad to hear it. The cloud is very picky with app ids.  Let's leave this open and I'll use it to clarify the docs as you suggest.

**Comment by PeteRager** [comment]
Updated readme.
