### ISSUE TITLE
Auto-create sensors for target temperature, heating, cooling, auxheat; OR Modify graph for more heating context

### ISSUE THREAD

**Issue by jhaagsma** [PeteRager/lennoxs30#280]
**Problem:**
I'm trying to see on the history graph what portion of my HVAC is working, with respect to my heat pump vs furnace (heat vs aux heat). Currently my balance point is at -5C, and we've been waffling around that point here for a few weeks now. So, in the same way that **cooling** is conveyed with blue and **heat** with orangey-red, i wanted to split heat into **Aux / furnace heat** with orangey-red and **Heat / heat pump heat** with yellowy-orange.

**Describe the solution you'd like**
I was going to try to just roll my own graph in apex-charts, but I realized that I don't have access to any of these data sources conveniently. It'd sure be nice if they were available! I am starting to look into templating (I saw some helpful stuff in Issue #59 ), but I feel like some of these things would better serve people out-of-the-box.

Alternately, if you could update the existing graph, to indicate aux heat vs heat, that would also be great.

**Details of your HVAC system (e.g heat pump, gas furnace, boiler, AC, external ventilation)**
Heat pump (which obviously works as AC in the summer) + Gas Furnace (Aux heat)

**Additional context**
My long term goal is to start getting a better idea of how much I use each, and start relating that to electricity/gas usage, but that is a bigger problem. For now just being able to see it would be nice. A couple weeks ago we were consistently below -10C, but now it's warmed up again, but not for long I suspect.

**Comment by PeteRager** [comment]
Home Assistant only allows specific values for hvac_mode or hvac_action as specified here:

https://developers.home-assistant.io/docs/core/entity/climate

So we do not have the option to add additional ones.  There is an aux attribute on the climate entity that should allow you to determine if the furnace of heat pump is running.  

https://github.com/PeteRager/lennoxs30#supported-data

and there are binary entities indicating if the heat pump is locked out

https://github.com/PeteRager/lennoxs30#binary-sensor-entities

Are those working on your system?

If so we should be able to construct a template that adds the new state and then publish it as an application note for others to use. 

Something like this should work.  You can test it in developer tools / templates.  Once it works create a sensor template and add it to your recorder configuration.  Then you can easily chart it.  It's a pretty common practice to create templates to shape that data for the UI.  

```
{% set hvac_action = state_attr("climate.air_conditioner","hvac_action") %}
{% set aux = state_attr("climate.air_conditioner","aux") %}
{% if hvac_action == "heating" %}
  {% if aux == True %}
heating-furnace
  {% else %}
heating-hp
  {% endif %}
{% else %}
{{hvac_action}}
{% endif %}

```

**Comment by PeteRager** [comment]
Did this solution work for you?

**Comment by PeteRager** [comment]
Closed due to inactivity

**Comment by jhaagsma** [comment]
Apologies, I haven't had time to test. Hopefully I'll have a bit more time over the xmas break to test & respond.
