### ISSUE TITLE
Aux / Emergency mode missing??

### ISSUE THREAD

**Issue by klingon888** [PeteRager/lennoxs30#282]
What happened to this [enhancement ](https://github.com/PeteRager/lennoxs30/issues/85) where there used to be a toggle for switching on/off aux/emergency heat mode for HP systems with aux heat.

I no longer see this option in HA GUI or is it buried somewhere? The "aux_heat" field still exists in HA but no option to set in the new GUI. Thanks.

![image](https://github.com/PeteRager/lennoxs30/assets/30375535/5848c340-3a7b-4935-80a9-d3ee2188fee6)
![image](https://github.com/PeteRager/lennoxs30/assets/30375535/095d8d2c-1914-40d8-8e4f-dc6d8d4122ec)

**Comment by PeteRager** [comment]
it's a good question, I don't know where that went to, maybe they removed it?

There is a service call called climate.set_aux_heat which you can use to turn it on or off

The climate entity has an attribute called supported features which indicates what capabilities the thermostat has, yours if set to 89.  The flag for AUX_HEAT = 64

so in binary

```
89 = 1011001
64 = 1000000
```

and the flag is getting set properly.

From an integration perspective it looks correct.  We may want to post this question on the HA community to see if someone else has seen it.

**Comment by klingon888** [comment]
Thanks Pete. The "climate.set_aux_heat" tip works for now. I'll post the Q on HA. I'm all for enhancements but taking away a working function is going a step backwards! Hopefully they wont make another "enhancement" and take away the climate.set_aux_heat service!
