### ISSUE TITLE
How often should diagnostic entities update?

### ISSUE THREAD

**Issue by 42Network** [PeteRager/lennoxs30#283]
I am noticing that none of my diagnostic-based entities, such as Cooling Rate, Blower Power, various CFM numbers, update anymore. Regular entities, such as temperature and humidity do update, however. Admittedly, I do not have my thermostat blocked from the Internet because I like to use the Lennox app. Is lack of diagnostic entity updates a symptom of letting my thermostat have internet access?

Here is a screenshot of diagnostic entities not updating:
![image](https://github.com/PeteRager/lennoxs30/assets/35043496/0365d05e-903b-4d00-8dcd-d044b85c4dd4)

FYI if I simply toggle the Diagnostic Level setting from 2 to 0 and back to 2, they will update (in the above screenshot, I had toggled 21 hours ago):
![image](https://github.com/PeteRager/lennoxs30/assets/35043496/cc8a3a7d-7908-4b96-87c6-7e70535b9bf3)

Here is another screenshot showing some entities updating, others not:
![image](https://github.com/PeteRager/lennoxs30/assets/35043496/40131ba5-c444-4047-8af0-c10160c09f29)

Any ideas on how I can troubleshoot?

**Comment by 42Network** [comment]
Hi. It may be similar, although in my case the diagnostic entities are available, just not with any recent values. Toggling Diagnostic Level causes a one-time update, but then they don't update any further. 

At the recommendation of my Lennox dealer, I did enable continuous air circulation in an attempt to better regulate humidity throughout our house, which has three zones (Main, which is our first floor minus master bedroom suite, Master, and Upstairs). Do you think this has triggered the internal Lennox bug you mention in #201? I can try to disable continuous air circulation from my thermostat panel and see if the integration starts getting diagnostics updates again.

**Comment by PeteRager** [comment]
Could be.  So in your case they are disabled permanently, meaning toggling diag level does just does a one time poll?   You may want to reboot the s30 see if that resolves.  Also from HA settings  integrations/lennoxs30 download the diagnostic file and post - this will have software versions in it.

**Comment by PeteRager** [comment]
With internet access enabled all the diagnostic information also streams out to Lennox.  They may not like that and/or the controller gets overwhelmed.  In the past the controller used to crash but perhaps they have fixed those.

**Comment by 42Network** [comment]
> I created this automation to toggle the diagnostic level from 2 to 1 and back, every 15 minutes, and that seems to be keeping everything updated continuously, without causing any of the sensors to switch to "Unavailable" like 2->0->2 does
> 
> ```
> alias: Fix Lennox S40
> description: ""
> trigger:
>   ...snip...
>     target:
>       entity_id: number.lennox_diagnostic_level
> mode: single
> ```

I have implemented your suggested automation and my metrics are updating more consistently now, thank you! I will continue to observer the behavior.

> Additionally, the crashing/rebooting issues mentioned throughout the documentation do not seem to be affecting my S40.
> 
> It has full internet access, and all of the alerts and dealer sharing features are enabled.

I too run my S40 with internet enabled and it seems to stay reliably connected to both Lennox cloud and HA.

> It _was_ disconnecting from the wifi a few times a day at first (without fully resetting and losing hvac controls), but that issue was reduced _significantly_ with the automation above, and further reduced with some tweaks to my wifi configuration (renaming 2.4GHz and 5GHz to separate SSIDs and connecting the S40 to 5GHz)

I haven't noticed any WiFi disconnects with my S40 on with my 2.4/gGhz single-SSID Unifi access points. In your case, how did you notice these WiFi disconnects?

**Comment by 42Network** [comment]
> I've seen this happen with my S40, especially with the inverter energy sensor. I noticed after a reload it would update every few seconds and display a min, mean, and max, but then after an hour or two it would get frozen.
> 
> I created this automation to toggle the diagnostic level from 2 to 1 and back, every 15 minutes, and that seems to be keeping everything updated continuously, without causing any of the sensors to switch to "Unavailable" like 2->0->2 does

Thanks for sharing your automation. It is working for me after updating the entity name for my system. I will keep observing, but my S40 diagnostic and parameter-based entities seem to be updated regularly now.


> Additionally, the crashing/rebooting issues mentioned throughout the documentation do not seem to be affecting my S40.

I agree with you that the S40 seems to not suffer as much as S30 when it has internet access enabled simultaneously with the HA integration.


> It _was_ disconnecting from the wifi a few times a day at first (without fully resetting and losing hvac controls), but that issue was reduced _significantly_ with the automation above, and further reduced with some tweaks to my wifi configuration (renaming 2.4GHz and 5GHz to separate SSIDs and connecting the S40 to 5GHz)

What symptoms did you notice with your S40 with a combo SSID? Mine stays connected 100% as far as I can tell with my Unifi APs.

**Comment by PeteRager** [comment]
If you look at the Lennoxs30.state object it has a count of reconnects.

The availability of the sensors is managed by the integration. This is why going from 2 to 1 doesn't make it unavailable.

https://github.com/PeteRager/lennoxs30/blob/dcf1b6f77934ccc1241c1a32de999f2d677bc4aa/custom_components/lennoxs30/sensor.py#L245

it sounds like Lennox may be turning off diags after a certain amount of time. What version of firmware are you on?

**Comment by 42Network** [comment]
I’m running S40 firmware 4.25.0070, dated Sep 10, 2023.

I added the automation suggested above and my entities seem to stay updated
now.

**Comment by PeteRager** [comment]
That is good information, I will update the diagnostics docs with this information and the sample automation.

The evidence so far points to this being related to having the thermostats be internet connected, as you both are running in that mode and we do not have a report of this problem occurring with the thermostats not internet connected.

What could be helpful is to turn on message logging, disable the automation and run until the diags stop updating.  That would allow us to see if there is a message / status update that can be used to detect the situation.  It may also give us some insight into where the message is originating from.

**Comment by 42Network** [comment]
Ok, good idea. I've enabled logging and disabled the automation and will let it run for a while.

**Comment by 42Network** [comment]
Ok. I disabled the automation and now my diag based entities are 4 hours stale. I bounced the Diag mode from 2 to 1 to 2 by hand and they didn't update and then I bounced it from 2 to 0 to 2 and they did update. This should all be captured in the message log. How should I give you the log file?

**Comment by PeteRager** [comment]
You can email it to Pete dot Sage at iCloud dot com

**Comment by 42Network** [comment]
Sent!

**Comment by PeteRager** [comment]
I analyzed the logs and don't see any notification in there that says diagnostics got turned off.

But there is an issue with the diagnostic level number entity as it only gets refreshed when the integration is loaded/reloaded or when a command is issued to set it.  So it is possible it is changing value and the integration may need to poll it.

if we want to test this,  disable the automation, wait for it to stop updating, reload the integration and see what the diagnostic level is.  If it's not 2 that means it is being changed and we need to poll it, if it is is 2 then Lennox is not updating this value when it disables diagnostics.

**Comment by PeteRager** [comment]
https://github.com/PeteRager/lennoxs30/releases/tag/2024.1.0
