### ISSUE TITLE
max_temp and min_temp warnings

### ISSUE THREAD

**Issue by stu247** [PeteRager/lennoxs30#284]
**Describe the bug**
I have a heat pump, so my system supports emergency heating. When I turn on aux_heat, I get two log warning messages:
```
 Logger: custom_components.lennoxs30.climate
Source: custom_components/lennoxs30/climate.py:280
Integration: Lennox S30/E30 (documentation, issues)
First occurred: 1:46:46 PM (1 occurrences)
Last logged: 1:46:46 PM
max_temp - unexpected system mode [emergency heat] returning default - please raise an issue
```
```
 Logger: custom_components.lennoxs30.climate
Source: custom_components/lennoxs30/climate.py:253
Integration: Lennox S30/E30 (documentation, issues)
First occurred: 1:46:46 PM (1 occurrences)
Last logged: 1:46:46 PM
min_temp - unexpected system mode [emergency heat] returning default - please raise an issue
```
The S40 successfully changes to emergency heat mode.  So everything runs fine.  However, the log message says to raise an issue, so I have created this issue.  This is a low priority for me.

**To Reproduce**
The following Yaml action was run:
```
    - service: climate.set_aux_heat
      target:
        entity_id: climate.lennox_zone_1
      data:
        aux_heat: true
```

**Expected behavior**
No log messages.

**Screenshots/Logs**
NA

**Version**
 - Home Assistant: 2023.12.3
 - This Integration: 2023.10.1

**Integration Configuration **
- Cloud or Local Connection: Local
- Inverter or Sensor Diagnostics Enabled: no

**Additional context**
NA

**Comment by PeteRager** [comment]
Thanks for the report.  The impact will be the climate entity will not use the min / max temperature ranges defined in the Lennox System and will instead use the HA defaults when in Emergency Heat Mode.  So I'd expect to see some weirdness with the min / max limits changing in the thermostat card when switching in/out of emergency heat mode.

I'll get it fixed.

**Comment by PeteRager** [comment]
https://github.com/PeteRager/lennoxs30/releases/tag/2024.1.0
