### ISSUE TITLE
Cannot change setpoint temperature because temperature is null

### ISSUE THREAD

**Issue by dmhuisma** [PeteRager/lennoxs30#300]
**Describe the bug**
Home assistant is not allowing me to change the setpoint temperature in the thermostat UI. It appears that this is because the temperature attribute of the climate entity is null. Here are my current climate attributes. It has been like this for about a week or so. I definitely have not received a thermostat update within this time frame, the version is currently 4.25.0070 (s40).

```
hvac_modes:
  - "off"
  - cool
  - heat
  - heat_cool
min_temp: 4.5
max_temp: 32
target_temp_step: 0.5
min_humidity: 15
max_humidity: 45
fan_modes:
  - auto
  - "on"
  - circulate
preset_modes:
  - schedule IQ
  - summer
  - winter
  - spring/fall
  - save energy
  - away
  - cancel hold
  - cancel away mode
  - none
current_temperature: 20.5
temperature: null
current_humidity: 37
humidity: 35
fan_mode: circulate
hvac_action: heating
preset_mode: none
aux_heat: "on"
allergenDefender: false
damper: 0
demand: 70
fan: "off"
humidityMode: humidify
humOperation: "off"
tempOperation: heating
ventilation: false
heatCoast: false
defrost: false
balancePoint: mid
aux: true
coolCoast: false
ssr: false
zoneEnabled: true
zoningMode: central
friendly_name: Home_Zone 1
supported_features: 93
```

Here is the UI, unable to change the temperature.

![image](https://github.com/PeteRager/lennoxs30/assets/57159257/e1ad0e37-65fe-43c3-a2b6-f9f5b7164032)

There was a home assistant log entry about this, but it has since gone because I have restarted after an update. I will add a comment if it comes back. It was specifically an error about the temperature attribute.

(Unrelated, but does anybody have a higher version for their thermostat? I am currently having heat pump issues and I'm told a new update came out late last year addressing it, but I do not know if I have it).

Thank you for this integration!

**To Reproduce**
None, it occurred on its own.

**Expected behavior**
I expect to be able to change the temperature within home assistant, and the temperature entity should not be null.

**Screenshots/Logs**
See above.

**Version**
 - Home Assistant: 2024.1.6
 - This Integration: 2024.1.0
 

**Integration Configuration **
- Cloud or Local Connection: local
- Inverter or Sensor Diagnostics Enabled: No

**Additional context**
N/A

**Comment by PeteRager** [comment]
You are running in Celsius and your Lennox system is running in emergency heat mode - that is what the aux = true means.  The code branch for handling this in Celsius is inconsistent with the code branch for Fahrenheit and will return Null in this case - which is a bug.  

Is that how the system is running?  Furnace is running instead of heat pump?

**Comment by dmhuisma** [comment]
My heat pump is not running very well, we have it running with aux because otherwise our house will get cold. So the aux setting was intentional on my part, didn't realize it might be contributing to the issue.

**Comment by PeteRager** [comment]
Got it, I have a fix in process for the API.  For now if you want to set it use the panel or take it out of aux mode change it and put aux back on.

**Comment by PeteRager** [comment]
I have fixed the API. I will create a new release of the integration tomorrow.

If you want to test the new version, you will need to edit the manifest.json file in the custom_components/lennoxs30 directory

Change this line from
```
  "requirements": ["lennoxs30api==0.2.12"],
```

to

```
  "requirements": ["lennoxs30api==0.2.13"],
```

And then restart home assistant and it will pull down the new version of the API with the fix.

If you don't feel confident about editing this file, that is ok, I will create a new version of the integration tomorrow AM.

**Comment by dmhuisma** [comment]
Thanks for the quick fix. Ive pulled in the new version. At first glance it appears to work but I'll report back of I see any issues.
