### ISSUE TITLE
Damper Position Reporting Error

### ISSUE THREAD

**Issue by garyak** [PeteRager/lennoxs30#31]
lennoxs30 reports all zone dampers at 100 on multi-zone system when dampers should report as zero for zones that are Off. For the single zone system, damper reports as zero as no dampers are installed.

**Comment by garyak** [comment]
Didn't wait a sufficient time for a sensor update.

**Comment by PeteRager** [comment]
How long did it take at startup?  Or was this after a successful startup that it took a while for the data to arrive?

I did change the app registration a bit.  What I found is when running two instances of HA with the integration; update messages were only received by one instance.  I think on the Lennox side there is a single mailbox per "App ID";  and hence when two integration are using the same App ID (it was hard-coded) whoever gets there first gets the message.

So now it generates a unique app id when it starts; which does seem to cause a bit more delay on startup from Lennox; but at least all the data goes to all HA instances that are running.  An alternative, if this becomes an issue, is to allow specification of the "app id" in configuration.yaml; and then it would always use that ID.

**Comment by garyak** [comment]
I had one of four zones cooling. All four zones reported 100. Single zone system reported zero. This was a few minutes after updating and core restart. I fiddled with the zones and checked for sensor updates, gave it a minute or so. Had not updated, all still 100. Did another core restart, returned to a single zone cooling, then checked status again. This time I had three zeros and a 100. Which was correct. Dampers  notoriously fail. It’d be nice to have an alert when damper fails to open/close.
