### ISSUE TITLE
Problem adding a second S40 in local mode using hostnames

### ISSUE THREAD

**Issue by graveland** [PeteRager/lennoxs30#317]
**Describe the bug**
I just installed 2 S40's, one for each furnace (upstairs and downstairs). I'm using a hostname, not an IP address, and the names are:
- `upstairs-hvac.<redacted>.net`
- `downstairs-hvac.<redacted>.net`

Upstairs worked just fine, but downstairs gets this error and fails to setup:
`homeassistant.exceptions.InvalidEntityFormatError: Invalid entity id encountered: lennoxs30.conn_downstairs-hvac_<redacted>_net. Format should be <domain>.<object_id>`

After a bunch of testing, I re-added the downstairs S40 with its IP address, and it worked. Strange that the hostname worked for upstairs, but not downstairs?

**Version**
 - Home Assistant: 2024.2.5
 - This Integration: 2024.2.1_r
 
**Integration Configuration **
- Cloud or Local Connection: both local, internet blocked at the router (no outgoing connections and no DNS allowed)
- Inverter or Sensor Diagnostics Enabled: tried both ways

**Additional context**
When adding the S40's, I installed the upstairs one first and it immediately worked. I've never gotten the downstairs one to add at all. I tried multiple combinations of removing the failed integration, restarting HA, and restarting the thermostat. The app_id for upstairs is `ha_up`, and I've generally tried `ha_down` for the downstairs one.

**Comment by graveland** [comment]
btw: Thanks for this repo- great work!

**Comment by PeteRager** [comment]
Yeah that's a bug, I fixed this in last release for cloud connections. I'll work on a fix.

what are the specific host names you have?  There may be a quick work around.

**Comment by PeteRager** [comment]
Please provide an example domain name preserving any - or _ or . In the name.

For example 

my_domain-pete.net


aa_bbbbbb-cccc.net

**Comment by graveland** [comment]
I did- my guess is that you need to replace `-` with `_` as well, as the `downstairs-hvac` portion is likely the problem, and you already replace `.`'s with `_`.

**Comment by graveland** [comment]
possibly moving to a whitelist form instead of blacklisting specific characters and just removing all characters not in `[a-z_]`

**Comment by PeteRager** [comment]
I think what happens is when end up with a double underscore and that causes HA to declare the entity id invalid.  When I made the change in #310 I only did it for the cloud branch.

**Comment by graveland** [comment]
According to the error message it's probably the `-` character. Replacing characters with `_` can potentially lead to duplicate underscores, and the fix to collapse them all to a single one can't be done is a single `replace` (`___` -> `__` with a single `replace`). If it's not too irritating, possibly just deleting all characters that aren't valid in an `entity_id` would be the safest bet?

**Comment by PeteRager** [comment]
I can't change the algorithm output as it'll break existing installs - at least when it outputs something valid.  I do agree that the suggested approach would be simple and robust.

**Comment by graveland** [comment]
Yeah, not surprising, but too bad!

**Comment by PeteRager** [comment]
I took your recommendation, other approaches were looking more difficult.  It will only cause a minor breakage for those who have more than one thermostat.

**Comment by PeteRager** [comment]
If you want to test it, grab the __init__.py file from here

https://github.com/PeteRager/lennoxs30/tree/connection-state-fix/custom_components/lennoxs30

Replace it in your custom component install and restart HA

**Comment by graveland** [comment]
Since that'll change existing installations (ip addresses drop their `_`'s), what about:

```python
self.connection_state = "lennoxs30.conn_" + re.sub("_+", "_", re.sub("[^A-Za-z0-9]","_",self._ip_address))
```

**Comment by PeteRager** [comment]
So that will "_+" will remove all double or triple underscores?

**Comment by graveland** [comment]
Yeah, `_+` means one or more `_` characters :)

**Comment by PeteRager** [comment]
Thanks for your help. I've tried to avoid learning regex for 20+ years...thanks for giving me my first lesson.

I've adjusted the changes.  They are in this branch:

https://github.com/PeteRager/lennoxs30/tree/2023.3.0

with this pull request

https://github.com/PeteRager/lennoxs30/pull/314

**Comment by PeteRager** [comment]
Should be addressed in latest release 2024.3.0.  Thanks for the help.

**Comment by graveland** [comment]
Thanks! I'll update and test! re: regex: I've used them too much in the last 20+ years. Fully understand not wanting to be tainted with them :D

**Comment by graveland** [comment]
Totally worked- thanks again!
