### ISSUE TITLE
Provide support for Fresh Air Ventilation Damper

### ISSUE THREAD

**Issue by blyons16** [PeteRager/lennoxs30#32]
The Ventilation command opens a damper to bring in fresh outside air (assuming the outside air is "fresh" of course. :)) and turns on the fan high to circulate through the house. This is effectively like a "whole house fan" without having to open windows or doors.

**Comment by PeteRager** [comment]
The following changes will be needed:

- Add attribute to climate entity to prevent indicate if the zone is currently ventilating.  Lennox provides this information in its zone status message.

- Add a switch entity to Home Assistant to control the ventilation damper to be open / closed.

- Lennox has the ability to set the duration for the ventilation damper to be open, need to determine best way to model this in HA, and may require adding a custom service method to the switch entity.

- Add attributes to the switch to track the remaining ventilation duration.  Lennox also has a diagnostic that provide total ventilation hours, which will be included
