### ISSUE TITLE
depreciation warning about is_aux_heat in 2024.10.0

### ISSUE THREAD

**Issue by TheWebMachine** [PeteRager/lennoxs30#320]
**Screenshots/Logs**
![Screenshot_20240404_010314_Home Assistant.jpg](https://github.com/PeteRager/lennoxs30/assets/1045052/68c19931-e2ba-4941-bda3-ffa385c4fe5c)

**Version**
 - Home Assistant: 2024.4.0
 - This Integration: 2024.3.0

**Comment by AdamPflug** [comment]
Announcment: https://developers.home-assistant.io/blog/2024/03/10/climate-aux-heater-deprecated/
Context: https://github.com/home-assistant/architecture/discussions/932

**Comment by tedski** [comment]
I'd like to help out with this one, but I'm new to the codebase.  Is this a good first issue to pick up and if so, are there any thoughts on which path to take for resolution?

**Comment by PeteRager** [comment]
Thank you.  I have it fixed locally in this branch

https://github.com/PeteRager/lennoxs30/tree/2024.4.0

I have not validated it on a live system.

**Comment by PeteRager** [comment]
The branch is finally released, apologies for the delays.  This provides a new select entity to enable the functionality.

https://github.com/PeteRager/lennoxs30/blob/master/docs/aux_heat.md

https://github.com/PeteRager/lennoxs30/releases/tag/2024.6.0

Note:  The issue will still be reported as we have not removed the capability from the integration yet, that will be released and removed on 2024.9.0 to give people a chance to migrate.

**Comment by PeteRager** [comment]
https://github.com/PeteRager/lennoxs30/releases/tag/20204.8.0
