### ISSUE TITLE
S40 Diagnostict data stops reporting after 3 hours

### ISSUE THREAD

**Issue by klkohl** [PeteRager/lennoxs30#324]
**Describe the bug**
After setting the Diagnostic Level to 2, diagnostic entity data is recorded for approximately 3 hours then flatlines.

**To Reproduce**
Reset the diagnostic level to 0 and back to 2. Wait approximately 3 hours.

**Expected behavior**
Once the diagnostic level is set to 2, I expect the entities to keep recording until the diagnostic level  changes.

**Screenshots/Logs**

**Version**
 - Home Assistant: 2024.5.2
 - This Integration: 2024.3.0
 

**Integration Configuration **
- Cloud or Local Connection: Local Connection
- Inverter or Sensor Diagnostics Enabled: Both

**Additional context**
My dealer upgraded me from a S30 to a S40 a couple of months ago. I didn't experience this problem with the S30, but I've been experiencing this problem ever since the change. 

I tried running the Fix Lennox S40 Diagnostics script, but when I try to save the script in Home Assistant I get the following error:
Message malformed: extra keys not allowed @ data['trigger']

**Comment by PeteRager** [comment]
That is a known issue with S40, see this issue for a sample automation to use.

https://github.com/PeteRager/lennoxs30/issues/283

I will add this to the documentation / samples.

**Comment by PeteRager** [comment]
> I tried running the Fix Lennox S40 Diagnostics script, but when I try to save the script in Home Assistant I get the following error:
> Message malformed: extra keys not allowed @ data['trigger']

post that script here and I'll look at it.

**Comment by klkohl** [comment]
After reading #283 It looks like the script is supposed to be an automation. That's probably why I was getting the error. I found the "script" here:
https://github.com/PeteRager/lennoxs30/blob/master/docs/diagnostics.md

alias: Fix Lennox S40 Diagnostics
description: ""
trigger:
  - platform: time_pattern
    minutes: "0"
  - platform: time_pattern
    minutes: "15"
  - platform: time_pattern
    minutes: "30"
  - platform: time_pattern
    minutes: "45"
condition: []
action:
  - service: number.set_value
    data:
      value: "1"
    target:
      entity_id: number.lennox_diagnostic_level
    enabled: true
  - service: number.set_value
    data:
      value: "2"
    target:
      entity_id: number.lennox_diagnostic_level
mode: single

**Comment by PeteRager** [comment]
Yes, that is an automation.  The docs say script which is incorrect. I will fix that.  You should be able to go into the automation editor, create a new automation, switch to YAML mode, and paste it in.

**Comment by klkohl** [comment]
I did that and it appears to be working. Thanks.

**Comment by klkohl** [comment]
Thanks.
