### ISSUE TITLE
Schedule Hold not populating in preset_modes

### ISSUE THREAD

**Issue by cmgrayb** [PeteRager/lennoxs30#330]
**Describe the bug**
"Schedule Hold" is returned by the S30 any time the fan or temperature is changed from the default, in property preset_mode.  This causes an error to pop up in the thermostat card on load, such as:
```Preset mode is not valid. Valid preset modes are: schedule IQ, Summer, Winter, Fall/Early Spring, Default, away, cancel hold, cancel away mode, none.```
The above list of modes is populated in property preset_modes (note plural)

**To Reproduce**
Steps to reproduce the behavior: create a thermostat card tied to the HVAC zone, change either the fan or temperature setting

**Expected behavior**
Schedule Hold should be a member of the list in preset_modes to prevent the above error

**Screenshots/Logs**
![image](https://github.com/PeteRager/lennoxs30/assets/79777799/7fa4cda3-7f1b-4387-a8d9-26877a342fe1)

**Version**
 - Home Assistant: 2024.6.*
 - This Integration: 2024.6.0
 

**Integration Configuration **
- Cloud or Local Connection: Local
- Inverter or Sensor Diagnostics Enabled: Sensor

**Additional context**
N/A

**Comment by PeteRager** [comment]
Thanks for reporting.  Should be fixable.

Couple of potential approaches. 

a) if the thermostat is in Schedule Hold, Schedule Hold will be added to the valid list of presets
b) if the thermostat is not in Schedule Hold, Schedule Hold will not be in the valid list of presets
c) any attempt to set the preset to "Schedule Hold" will generate an error. 

Alternate approach

a) always have schedule hold in the list of presets
b) any attempt to set the preset to "Schedule Hold" will generate an error. 

Thoughts?

**Comment by cmgrayb** [comment]
Personally, I would probably approach it the same as cancel hold, since that is not an actual preset. Barring that, it would appear that Schedule Hold should be available on every unit, so probably statically add it to the list?

**Comment by cmgrayb** [comment]
In further thought, the first approach makes more sense and it appears you are already headed that direction in the PR.

**Comment by PeteRager** [comment]
> . I don't suppose we can tell what preset we're coming from to trap the error and set the preset back to a valid one?

I think we can.  Lennox uses numerical ids for the schedules. So 1-16 are the user presets. If you are on schedule id 3 and override it, they add 32, so that becomes schedule id 35.  When we cancel it, it goes back to 3.  How would you see this working?

**Comment by cmgrayb** [comment]
That sounds promising

**Comment by PeteRager** [comment]
So it turns out that we can't add that preset in sometimes.  So we are going with

a) always have schedule hold in the list of presets
b) any attempt to set the preset to "Schedule Hold" will generate an error.

Note, when attempting to do B in the climate card and error is reported to the UI; however the climate cards "optimistic" mode will show schedule hold temporarily until it's timer expires or the card is reloaded.

**Comment by PeteRager** [comment]
This should be fixed in
