### ISSUE TITLE
Integration with M30 suddenly stopped working

### ISSUE THREAD

**Issue by dhirsch** [PeteRager/lennoxs30#333]
**Describe the bug**
My cloud connection to M30 suddenly stopped working. All devices and entities are unavailable. I have tried removing the device in HA and re-adding but it does not find any devices when configured. 

**To Reproduce**

**Expected behavior**

**Screenshots/Logs**
The Lennox System with id [d85534f0-2a02-42fe-8e06-7b2d257a49b0] is not connected to the Lennox Cloud. Cloud Status [offline]. Please check your thermostats internet connection and retry.

**Version**
 - Home Assistant: 2024.7.3
 - This Integration: 2024.6.1
 

**Integration Configuration **
- Cloud or Local Connection: Cloud
- Inverter or Sensor Diagnostics Enabled:

**Additional context**
The iComfort app still works, so the device is connected to the cloud

**Comment by Smitters1501** [comment]
I have the same issue with my M30 too.
My version was 2024.5.5 and this morning it's just stop working
I try to upgrade to 2024.7.3 and reinstall the integration 2024.6.1 but still not working

**Comment by bennydiamond** [comment]
Same deal here.
Just bought a house with a M30 preinstalled. No more access...

Crowdstrike maybe?

**Comment by PeteRager** [comment]
With the 3 of you reporting the same issue. There must be a problem with the Lennox cloud.  They do run on Microsoft Azure. I'll run a test with my S30 reconnecting it to the cloud to see if that works.

Everyone has the same error message?  Anything else in the logs?

**Comment by PeteRager** [comment]
Let's turn on message logging, follow the instruction here:

https://github.com/PeteRager/lennoxs30/tree/master#reporting-bugs

Enable the logging, restart HA, let it run for 5 minutes, upload the log file.

The other item to try is changing the APP ID in the integration config.  You should be using the default one.  

mapp079372367644467046827001

Try changing the last 4 digits to something else.  Delete the message log, Restart HA, post that log.

**Comment by bennydiamond** [comment]
[home-assistant.log](https://github.com/user-attachments/files/16321438/home-assistant.log)
[s30_local.log](https://github.com/user-attachments/files/16321439/s30_local.log)

Enabled debug logs as instructed.
No change to APP ID.

**Comment by PeteRager** [comment]
> [home-assistant.log](https://github.com/user-attachments/files/16321438/home-assistant.log) [s30_local.log](https://github.com/user-attachments/files/16321439/s30_local.log)
> 
> Enabled debug logs as instructed. No change to APP ID.

Thank you,  the logs shows that your thermostat is connected to the cloud.  We are also able to login and subscribe to the topics.  However, we are not receiving any subscription replies from Lennox. The subscriptions are tied to the app_id. I would try changing the App ID and see if that fixes.

**Comment by bennydiamond** [comment]
I removed my instance and re-added using APPID `mapp079372367644467046821234`.


[home-assistant.log](https://github.com/user-attachments/files/16322790/home-assistant.log)
[s30_local_newAPPID.log](https://github.com/user-attachments/files/16322791/s30_local_newAPPID.log)

No device or entities are created.

Sorry for taking a while, I just moved in this new house. Lots of stuff to unpack :)

**Comment by bennydiamond** [comment]
[config_entry-lennoxs30-01J39F8RFQBGZV2GAZPFP9J0HP.json](https://github.com/user-attachments/files/16324347/config_entry-lennoxs30-01J39F8RFQBGZV2GAZPFP9J0HP.json)

If it could be relevant...

**Comment by PeteRager** [comment]
It is behaving the same.  Either something is broken in the Lennox cloud or they changed the API.

Are you able to use the Lennox app to control when not connected to your local WIFI?  What version of the App is installed?

I'll have some time this upcoming week to test.

**Comment by bennydiamond** [comment]
Ok lol, I just deleted and re-created my instance with the default APPID and everything is suddenly working again!

To answer your question:
Seemingly, I never lost the ability to control the M30 thermostat through my phone.
I've been using Android "iComfort" app version 3.92.014 these past few days (moved in this house a week ago).

**Comment by PeteRager** [comment]
Sounds like Lennox fixed the problem.  There is nothing the integration stashes between runs. 

The app has the ability to talk directly to the thermostat when on the same network - at least for the S30 and E30 that have local control.  The REST API we use for cloud communication is the same one as they use in the app (or at least is used to be).  Are you able to see if there are any open network ports on your thermostat?

**Comment by bennydiamond** [comment]
Unfortunately, nmap shows no open port

```
# nmap -p- 10.0.2.100
Starting Nmap 7.94SVN ( https://nmap.org ) at 2024-07-21 09:55 EDT
Nmap scan report for 10.0.2.100
Host is up (0.016s latency).
All 65535 scanned ports on 10.0.2.100 are in ignored states.
Not shown: 65535 closed tcp ports (reset)
MAC Address: 80:C9:55:xx:xx:xx (Redpine Signals)

Nmap done: 1 IP address (1 host up) scanned in 47.30 seconds
```

**Comment by dhirsch** [comment]
It started working again for me today after removing and adding the integration.

**Comment by Smitters1501** [comment]
Start back working also for me today. 
Look like crowdstrike issue

**Comment by PeteRager** [comment]
Thanks for checking.  Looks like still no local connection.

We should be able to close this issue, if it comes back we can open a new one.

**Comment by bennydiamond** [comment]
Fine with that!

Thanks for the support @PeteRager

**Comment by RPMarcello** [comment]
> Thanks for checking. Looks like still no local connection.
> 
> We should be able to close this issue, if it comes back we can open a new one.

I still have this issue.  I can access thru the app and the website but nothing in HA.
