### ISSUE TITLE
Lennox Host Address changed

### ISSUE THREAD

**Issue by Paulbhyo** [PeteRager/lennoxs30#336]
Hello,  I recently had a problem with my router and the IP address of my IOT networks was reset,  so several devices ended up with a different IP address.  The Lenox thermostat was one of the devices that changed.  Is there a way to quickly tell the integration where to look for the new address?.  

Some other integrations have he host field on the "reconfigure" 3 dots.  I wasnt sure if that was possible,  or if the address is stored someplace that I could edit it quickly.  

Thanks!.

**Comment by PeteRager** [comment]
The integration does not have that capability.  Approaches to try:

a) configure the router to give Lennox the same ip address it had
b) delete and readd the integration - but if you've changed entity names or entity ids these changes will be lost
c) shutdown ha, edit the .storage/core.config_entries and change the ip address in the host and title fields (do not change it in unique_id), restart HA
