### ISSUE TITLE
Typo in latest version breaks semver

### ISSUE THREAD

**Issue by tedski** [PeteRager/lennoxs30#337]
**Describe the bug**
The latest release appears as version `20204.08` (note the extra zero)

**Additional context**
I believe this will cause issues when comparing versions to determine a new version has appeared.

**Comment by PeteRager** [comment]
Thanks for the report.  It looks like the label on the release had the typo.  I edited the release and added the correct label.

**Comment by tedski** [comment]
Looks good on my end now.
