### ISSUE TITLE
C vs F units

### ISSUE THREAD

**Issue by graveland** [PeteRager/lennoxs30#345]
**Is your feature request related to a problem? Please describe.**
I'm in Canada and I prefer metric values. The reported temperatures are in C, but all the configuration values are F. For example, right now it says the outdoor temperature is 4.5°C, but upstairs_par_Aux_Heating_Activation_Threshold is asking for °F.

**Describe the solution you'd like**
This integration determines the display values by looking at HA's config.units, and sets is_metric. It should use that for the settings input values as well as the display values.

**Details of your HVAC system (e.g heat pump, gas furnace, boiler, AC, external ventilation)**
Two S40's, one upstairs and one downstairs, both with the same issue.

**Additional context**
HA version 2024.10.3, lennoxs30 version 2024.8.0

**Comment by PeteRager** [comment]
That doesn't seem optimal.

Lennox is only sending the values in F.  Example for one of parameters

https://github.com/PeteRager/lennoxs30api/blob/9f9f92504ed972f6c147aa7416ea7dbc3740830e/tests/messages/equipments_lcc_singlesetpoint.json#L2341

In there are the valid ranges and the step size which are valid.

Are your equipment diagnostic values being translated to C?

Here's an example:

https://github.com/PeteRager/lennoxs30api/blob/9f9f92504ed972f6c147aa7416ea7dbc3740830e/tests/messages/equipments_lcc_singlesetpoint.json#L5180

I think HA is supposed to translate values transparently to the correct units. Perhaps this isn't working for input_numbers.  

If you could turn on message logging and post some snippets (or the entire message log) of a parameter and a diagnostic that are temperatures, then we can verify what Lennox is sending.

**Comment by PeteRager** [comment]
I think the issue is the device_class is not being set for the number entity and HA will only do the units conversion if the device class indicates its a temperature.

**Comment by PeteRager** [comment]
Unfortunately the solution is not simple.  Many of the parameters that have units of F do not work well when translated

For example:

```
                        {
                            "id": 37,
                            "parameter": {
                                "defaultValue": "0.25",
                                "descriptor": "range",
                                "enabled": true,
                                "format": "16q4",
                                "name": "SSP Heating Cancel Coast Counter Increment Slope",
                                "pid": 198,
                                "range": {
                                    "inc": "0.125",
                                    "max": "0.75",
                                    "min": "0"
                                },
                                "unit": "F",
                                "value": "0.25"
                            }
                        },
``` 

This when translated to celsius shows a large negative number; which is incorrect and will be difficult to use.  The same is true for parameters like temperature calibration which allow an offset to be added/subtracted from the setting.

So we will need to specify a very specific set of parameters that should be translated.  Is it just the one you see or are there oethers?

**Comment by graveland** [comment]
What do you consider a large negative number? Also for the example you just posted, a zero-based offset certainly doesn't mean 0°F or 0°C, so I don't really care about that. I could be convinced that not even displaying a unit would make sense for those as long as the inputted value was quantized to the nearest `inc`, but displaying F for those is totally fine.

It's the actual temperatures that don't make sense to me since I've basically never used F at all. I'd suggest any F input values that are asking for an actual temperature should be translated, but if I had to pick only one it would be `par_Aux_Heating_Activation_Threshold` since I believe that's the one I'd use to control auxiliary heating, correct?

My actual reasoning behind looking into this is to automatically switch between aux (gas), and no aux (electricity) based on what my solar panels are currently producing.

**Comment by PeteRager** [comment]
The example posted is the JSON that Lennox sends to the integration.

The simple approach is to enable the temperature device_class for any parameter that has a unit of "F" and then HA will automatically translate them to Celsius.  

However, since the offsets and calibration parameters have units of :"F" - that solution won't work.  Instead we need to make a list of parameters that represent absolute temperatures should be translated to Celsius - and we will leave any temperature offsets in F.

Summary:

- absolute temperatures - these should be translated to Celsius by HA
- offset temperatures - these will not be translated to Celsius. We will leave the units of F on the number,.

**Comment by PeteRager** [comment]
> it would be `par_Aux_Heating_Activation_Threshold` since I believe that's the one I'd use to control auxiliary heating, correct?
> 
> My actual reasoning behind looking into this is to automatically switch between aux (gas), and no aux (electricity) based on what my solar panels are currently producing.

That parameters won't do that.  That; is intended to allow aux heat to come on if the HP is running at 100% and the delta between your setpoint and current temperature exceeds this threshold.  In other words run both heat sources to get the house up to temperature faster.

There are a couple of tactics.  There is a mode called Emergency Heat - this runs the furnace.  So if you want to run the furnace activate this mode.  There is also a balance point which indicates when to switch from HP to Furnace based on outside ambient temperature.

**Comment by graveland** [comment]
Is the correct one for the outside ambient switchover par_Low_Balance_Point? And the thermostat setting is *_hvac_mode, switching it between heat vs emergency heat, correct?

**Comment by graveland** [comment]
I'll run your PR and let you know how it works for me, thanks!

**Comment by PeteRager** [comment]
> Is the correct one for the outside ambient switchover par_Low_Balance_Point? And the thermostat setting is *_hvac_mode, switching it between heat vs emergency heat, correct?

Yes. The Lennox docs have details on how all there parameters work.

https://tech.lennoxintl.com/C03e7o14l/VIu12Ch2uV/Corp1817-L8f.pdf

Yes, the select entity for the zones hvac mode - set it to emergency heat.  

There are also a set of binary sensors the indicate the states of the heatpump lockout.

**Comment by PeteRager** [comment]
This should be resolved in https://github.com/PeteRager/lennoxs30/releases/tag/2024.11.0
