### ISSUE TITLE
No entities available for climate.set_aux_heat despite furnace and heat pump being present

### ISSUE THREAD

**Issue by tedski** [PeteRager/lennoxs30#348]
HA version: 2024.10.4
Integration version: 2024.8.0
Using Diagnostics?: No

I have both a gas furnace and a heat pump configured in dual fuel mode.  I can select Emergency Heat mode from the thermostat without issue.  When attempting to use `climate.set_aux_heat` to enable emergency heat mode from HA (Developer Tools -> Actions), there are no available entities for that action.  

Logs attached
[s30.log](https://github.com/user-attachments/files/17601093/s30.log)

**Comment by PeteRager** [comment]
Climate.set_aux_heat has been deprecated by HA and has been removed from the integration. 

Please consult the documentation.
https://github.com/PeteRager/lennoxs30?tab=readme-ov-file#supported-operations

You will want to use the select entity and use the select_option action.

**Comment by tedski** [comment]
🤦 I should have known that, having helped QA that change.  Apologies, using the select entity works exactly as expected.
