### ISSUE TITLE
Schedule override with Time

### ISSUE THREAD

**Issue by PeteRager** [PeteRager/lennoxs30#36]
When creating a schedule override in the Lennox App, you are presented with 3 options:

- Until next schedule period’
- For a duration (e.g. 1 hour, 2 hours)
- Until cancelled

Currently the integration uses the first setting.  The request is to support the second option also.

**Comment by PeteRager** [comment]
The current climate interface in HA does not support different override types.  Therefore we will need to invent something.  There are two approaches that could work that I’d like feedback on.

Option 1.  Put something in configuration.y’all that specifies which of the three choices to use every time a schedule override is used.
Option 2. Add a service method to allow this to be specified at run-time

With either approach we’d also want a climate attribute to track the current mode and or time remaining

**Comment by rob51i03** [comment]
Option 2 would offer the greater flexibility and would be my personal preference. If the duration were given in the format hh:mm:ss that would align with similar functionality elsewhere in HA.

**Comment by PeteRager** [comment]
@rob51i03 - would you use this capability?  

Looking back, the request came from KLM on the HA forums, who has not answered yet and it is possible the real request is for the Climate card to prompt for the override mode - just like the thermostat / app does - that would require a custom card or a change to the climate interface and standard card - which is a broader scope of work.

Just want to make sure I’m creating a solution that will be used. 😊

**Comment by rob51i03** [comment]
I doubt I would use a custom card. Although I use the climate card in HA my main focus is event-driven automation - if I need to interact directly with the S30, I'd most likely go straight to the thermostat or use the Lennox app.

**Comment by PeteRager** [comment]
Aged too long, reopen if you want this
