### ISSUE TITLE
S30 Integration has orphaned

### ISSUE THREAD

**Issue by Koomafloo** [PeteRager/lennoxs30#37]
System has orphaned the S30 after reboot of HA for host server maintenance. 

![image](https://user-images.githubusercontent.com/87790863/127785810-ab654440-7d46-43b0-80da-ca06f16740df.png)
![image](https://user-images.githubusercontent.com/87790863/127785830-027cf2ef-3f6d-4d22-85f3-c93213f19524.png)

**Comment by PeteRager** [comment]
Please provide the errors that appear in the home assistant log.  There should be some.  

Try restarting again.  If that does not fix then please enable debug logging and email me that file.

**Comment by PeteRager** [comment]
The name of your entity seems odd.  Unless you or your HVAC guy named your S30 “SYSTEM”.  Are there other climate entries that have been created?  I have seen a very intermittent issue with data messages arriving atypical order that causes entity to be created with bad name.  It’s possible that hasn’t been fixed completely.  Thanks

**Comment by PeteRager** [comment]
Any update on this?

**Comment by Koomafloo** [comment]
Issue seems to be with S30 and connectivity, it has been resetting itself over the last few days. This first occurred when it dropped the network, which I didn't notice until a few days later. It appears the system was setup fairly hastily, which based on the installers, I'm not surprised at...

**Comment by PeteRager** [comment]
Thanks for the update.  Yes, the thermostat needs to be connected to get data.   I do know the Lennox App displays a blank screen when the S30 is offline.

It would be interesting to see the errors in the log, to  make sure the integration is handling this failure mode properly and continuing to retry the connection.    

The lennoxs30.state entity should show the status of the connection, you may be able to trigger an alert when it becomes disconnected. 

The integration should also retry every 1 minute to reconnect and should reconnect once the S30 is available again.

**Comment by PeteRager** [comment]
While this won’t solve your device. Wing offline WiFi issue, I would recommend upgrading to v 0.0.8 as there is an issue when the integration goes through its reconnection process - for example if your device is offline initially and then becomes available later.

**Comment by PeteRager** [comment]
Please reopen if occurs again an additional info is available.
