### ISSUE TITLE
Problems with v0.0.8 - climate.turn_on

### ISSUE THREAD

**Issue by rob51i03** [PeteRager/lennoxs30#44]
Recently upgraded to v0.0.8 to implement and test the "away" and "cancel away mode" presets. Have found that 
sending the command climate.set_preset_mode now results in unpredictable behaviour - either the S20 doesn't respond at all, or goes into preset modes not commanded. For example, sending the "away" preset mode might result in a "climate.turn_off", or sometimes takes the S20 out of preset mode and into basic heat/cool mode.
Once this has happened, other commands such as climate.turn_off fail to work or also result in unpredictable behaviour.
A restart of HA doesn't fix this.

**Comment by PeteRager** [comment]
That does not sound good.  Are you able to control the S30 from it's panel?

What we'd want to do next is capture the debug logs to see what is going on and understand the configuration of your system.  The readme has an example of what to put into the configuration.yaml.

Start the system up, run through a sequence of steps, provide that sequence to me and email the log file to pete dot sage at icloud dot com

**Comment by PeteRager** [comment]
The service does not implement climate.turn_on I would avoid using that call as the base class will turn on each individual mode - this may be one of the issues you are encountering.  Instead use climate.set_hvac_mode and specify the mode you are turning on.

This is what HA does, it will run through each of these mode and turn it on, that will cause your S30 to first go into HEAT_COOL mode, then into HEAT mode, then into COOL mode.

        # Fake turn on
        for mode in (HVAC_MODE_HEAT_COOL, HVAC_MODE_HEAT, HVAC_MODE_COOL):
            if mode not in self.hvac_modes:
                continue
            await self.async_set_hvac_mode(mode)
            break

I will fix the S30 integration to override this method and return a not_implemented.  To turn on the S30 you need to specify which mode you are going to run in.

**Comment by rob51i03** [comment]
Thanks for this info, I was unaware that climate.turn_on isn't applicable to the S30. I've come from the ecobee world, where it's necessary. I have changed my automations to remove that call. 

As it happens, I was in HA when your message appeared. I was trying to replicate yesterday's unpredictable behaviour and cannot. Everything seems rock solid today. But I have debug-level logging turned on now - I'll leave it on for 24 hours and if something goes pear-shaped at least it will be captured.

**Comment by PeteRager** [comment]
Sounds good.  

 On climate.turn_on, I will add a fix and attach it to this issue so that if someone does call that function it doesn’t thrash the thermostat by rapidly cycling modes.  I will also update the docs and file an issue for HA as this default implementation doesn’t seem like a good solution.

Another consideration.  There are two away modes in the S30.

1) Manual Away Mode - this is invoked manually by pressing the away button on the panel.  This is also what the away mode preset invokes
2) Smart Away Mode - this is a tied in with the Lennox phone app and uses a geofence and then toggles smart away mode.

I have not tested the interaction of these two modes.   Could be worth checking if Smart Away is enabled, to see if this is a potential source of the issues you saw.

**Comment by rob51i03** [comment]
I don't have smart away enabled. I don't think my other half would be happy if the system went into away mode when I went out for a ride on my bike :)

I suspect my issues yesterday were caused by the above climate.turn_on issue and (possibly) instability on my internet line. I don't see any unexpected behaviour at this point; all appears to be solid.

**Comment by PeteRager** [comment]
There are http statistics captured as attributes of the lennoxs30.state entity.  These counters may help.  The integration should log errors on network failures.  Some folks have had issues with the S30 losing connection to the network.

My analysis on climate.turn_on was wrong.   Apologies.  If you call that it should put your system into HEAT_COOL mode.  Not cycle through all available modes.  But being explicit is good.

If you are running a preset and then setting the hvac mode or changing the temperature it creates a schedule override of the current schedule up until the next schedule change.

I do not know, if toggling away mode when a schedule override is in place returns to the override or reverts to the schedule.

**Comment by PeteRager** [comment]
Please reopen / create a new issue when this occurs again.
