### ISSUE TITLE
Showing heat/cool setpoints when in heat or cool only.

### ISSUE THREAD

**Issue by highincolorado** [PeteRager/lennoxs30#57]
Found that in all 3 modes, heat, cool and heat/cool, the thermostat card will display 2 setpoints despite being in only a single mode. As well as showing 3 adjustable setpoints on the thermostat card settings page.

![Settings card](https://user-images.githubusercontent.com/60855018/137978187-dd7121cc-5e51-4b3d-afdd-81084e3333fc.jpg)

**Comment by PeteRager** [comment]
Starting work on this.

Note, there is a similar issue reported here.   Are you using “Perfect Mode”?

https://github.com/PeteRager/lennoxs30/issues/63

**Comment by highincolorado** [comment]
No, I didn’t even know there was such a mode. I am able to adjust the temperature
________________________________

**Comment by PeteRager** [comment]
> I have the same issue with the stock climate controls in HA:
> 
> ![image](https://user-images.githubusercontent.com/375080/139166725-28124b91-7d36-4ca8-adb6-baea57cf128e.png)

The Lennox has a Cool and a Heat setpoint. In your system they are 79 and 69.

if your system is in heat mode we’d want to show just 69, and if it was in cool mode we’d want to show just 79.

if it’s in heat and cool mode then we’d show both like in your pic.
In your pic the system is in off mode - what should we show?

**Comment by highincolorado** [comment]
Not my picture but my input would be to just show the set point and Off. Any cool seating in a heat mode or heat setting in a cool mode is ambiguous as it is not a setting on the thermostat in those modes. Possible it is showing whatever the range max is set to


________________________________

**Comment by highincolorado** [comment]
Example from the Lennox iOS app. [Image.jpeg]
________________________________

**Comment by magnetic157** [comment]
@PeteRager 

If the thermostat is off, I would think it would best to display the current indoor temp only without the adjustment bar or set temperature.  Perhaps a label saying off would be helpful too.

**Comment by magnetic157** [comment]
![8F38A351-E76D-421A-80F4-61FC03347F45](https://user-images.githubusercontent.com/78054864/139510065-59e547dc-f711-4d6a-9321-0c823358abc0.jpeg)
![1723F45D-B5D8-4305-A034-6BF3C79A8C36](https://user-images.githubusercontent.com/78054864/139510067-15630b0c-f7a6-4914-8b8e-aa9bdc17f7cb.jpeg)
![7230CF6A-CA25-4619-8BC6-3A64523D0C53](https://user-images.githubusercontent.com/78054864/139510069-5185382b-bdd3-48f5-b834-171d9dcb1c6f.jpeg)
![7D3817A2-A6C2-4615-A618-84ABD47D6105](https://user-images.githubusercontent.com/78054864/139510071-6a93e435-3801-4b00-a4b4-bf0a0647e729.jpeg)

**Comment by PeteRager** [comment]
Thanks for all the feedback in this.  My S30 is a cool only system and hence only has 1 setpoint,

I have this issue resolved in my test system and it should work exactly as the pictures above show.

We have a few more issues we are working on and will package all into a release likely before end of week.

**Comment by PeteRager** [comment]
Resolved in upcoming 0.1.2 release

**Comment by PeteRager** [comment]
https://github.com/PeteRager/lennoxs30/releases/tag/v0.1.2

Please open a new issue for any problems / changes.
