### ISSUE TITLE
Auto create temperature and humidity sensors for each zone

### ISSUE THREAD

**Issue by magnetic157** [PeteRager/lennoxs30#59]
Are there any plans to incorporate sensors the current indoor temperature and humidity?

**Comment by PeteRager** [comment]
Yeah, I think we should do this.   I’ll add an option to the configuration to create humidity and temperature sensors for each zone.  Be in the next release.  Week or so.  

The workaround is To manually create a sensor template to extract these attributes from climate entity as described here:

https://community.home-assistant.io/t/access-the-temperature-value-from-a-climate-entity/153429

**Comment by PeteRager** [comment]
Code is working, testing and should have a release later this week

![image](https://user-images.githubusercontent.com/76050312/139741528-c92a3d45-d243-4b0c-ad11-010e474142b4.png)

**Comment by PeteRager** [comment]
Resolved in upcoming 0.1.2 release
There is a configuration parameter (documented in readme.md) that when set automatically creates these sensors

**Comment by PeteRager** [comment]
https://github.com/PeteRager/lennoxs30/releases/tag/v0.1.2

Please open a new issue for any problems / changes.
