### ISSUE TITLE
Update configuration parameter "ip_address" to hosts

### ISSUE THREAD

**Issue by deviantintegral** [PeteRager/lennoxs30#67]
I was reading the last few PRs on local polling support (nice!), and it looks like the setting is validated to IP addresses only. Could it support hostnames too? For devices with integrations like this, I usually would set a static IP and hostname in my router.

I did check, and the thermostat isn't setting a hostname for itself in its DHCP request, unlike other devices like cameras that will often advertise a unique hostname.

**Comment by PeteRager** [comment]
The IP address does not have validation on it, so you could pass in a hostname and if DNS can resolve it, it should work.  If it isn’t setup in DNS, then assign like you suggest, set an IP to the S30 in the DHCP configuration of your router - so it stays consistent.

1.

**Comment by deviantintegral** [comment]
Excellent! I filed a small update to the README. I'd suggest renaming `ip_address` to `thermostat_address`, but it's not awful to keep it if you don't want to break existing configs.

**Comment by PeteRager** [comment]
Thanks for the PR!

Yeah, I think we should change the name.   Also, we need to provide support for multiple S30s and this really needs to be a list of host names.   With the cloud connection it gets all homes and all S30s with the account vs a local connection which connects to just 1 S30.

**Comment by PeteRager** [comment]
I've updated the parameters to be hostnames which sets us up to provide a comma separate list in the next release.
