### ISSUE TITLE
Support UI Based Configuration & Devices

### ISSUE THREAD

**Issue by HyperActiveJ** [PeteRager/lennoxs30#74]
I started some work on supporting UI based configuration of this component, and grouping the entities into devices.
Link:  https://github.com/HyperActiveJ/lennoxs30
Feedback appreciated.
Running into merge conflicts due to the pace of development this week.
Tasks:
1. Support migration from YAML
2. Support all configuration options including optional
3. Cleanup

**Comment by PeteRager** [comment]
Proposed design for config flow:

Step 1:  Have the user select cloud or local
Step 2:  Direct the user to a cloud or local config specific page.  (e.g. user/pass - cloud page, ip_address - local page, app_id)
Step 3: During validation of the page, attempt to connect using the info provided
Step 4: Allow settings to be configured (scan rates, create sensors, etc.)

After configuration is complete, allow setting in step 4 to be changed.

**Comment by PeteRager** [comment]
Going make a release next week.  Looks like we need more time on this and will get it in the next drop?

**Comment by PeteRager** [comment]
https://github.com/PeteRager/lennoxs30/releases/tag/v0.2.0
