### ISSUE TITLE
Add support for auxiliary heat. 

### ISSUE THREAD

**Issue by PeteRager** [PeteRager/lennoxs30#85]
Some Lennox HVAC systems have auxiliary heat as a backup / augmentation for the heat pump, hence it would be helpful to know when the aux system is running.  The request is to make this data available.

**Comment by PeteRager** [comment]
A proposed solution is to add an attribute to the climate entity representing the zone and to update this attribute when the auxiliary heat goes on / off.  There is a field in the Lennox zone status message called “aux”, when this is true the auxiliary heat is on. 

The climate entity in HA has an interface to turn aux heat on / off - is it possible to do this via the Lennox app?

**Comment by highincolorado** [comment]
If issue #70 is successful telling if the aux alone is running will be possible. Data sent.

**Comment by PeteRager** [comment]
> If issue #70 is successful telling if the aux alone is running will be possible. Data sent.

I did not get the log file via email.  Perhaps too big?  Zip and try again?

pete.sage at  iCloud.com

**Comment by PeteRager** [comment]
I have the code to capture the aux flag.  What I do not know yet is how to detect the system has the aux capability, that information should be somewhere in the config in the debug logs.

**Comment by highincolorado** [comment]
hat about the:
"indoorUnitType": "furnace",
@11:58:36

Does your unit have an indoor unit type? This could be resistive as well maybe?
Theres also a:
"outdoorUnitType": "heat pump"

hich maybe if missin gmeans it's a furnace only?
Just spitballing here.

**Comment by highincolorado** [comment]
I poked around at the app and found a selection for emergency heat which has the icon that is shown when the aux heat is running. Possible this would run furnace only? Will test when it is cooler again. 
![C6137067-CC0B-43D1-8894-3BCE68A86D06](https://user-images.githubusercontent.com/60855018/140664178-b8a47242-19e6-49bf-8898-162ad7ec149f.png)

**Comment by PeteRager** [comment]
> What about the: "indoorUnitType": "furnace", @11:58:36
> 
> Does your unit have an indoor unit type? This could be resistive as well maybe? Theres also a: "outdoorUnitType": "heat pump"
> 
> which maybe if missing means it's a furnace only? Just spitballing here.

Yeah, that may be it.

**Comment by PeteRager** [comment]
I found this note.

Emergency heat - All heat pumps operating in northern climates (below 35°F) normally need a supplemental heating source. Usually it is in the form of electric heating provided by the indoor unit. Other sources could be gas, oil, or hot-water back-up systems as well. The supplemental heat is also referred to as "second-stage" or "back-up" heating, with "first-stage" being the heat pump only. Emergency heat is when you use your supplemental heat (2nd stage) by itself, without the use of your heat pump (1st stage heat). Option is not available for non-heat pump systems.

We’d need to see what systemMode is set when you engage emergency heat.

**Comment by highincolorado** [comment]
Should be able to test that tomorrow, be in the 40’s in the morning.

**Comment by PeteRager** [comment]
@highincolorado - great there is an interface in climate to control aux heat. I do need the log file, what we do is cur out the large config messages, anonymize them, and feed those into our code to be able to simulate your setup.  Likewise with the smaller status messages, to make sure we catch changes.  My system is AC only.  Not sure if logfiles were sent and failed on my side?

**Comment by highincolorado** [comment]
Energency heat l
[Emergency heat.zip](https://github.com/PeteRager/lennoxs30/files/7498963/Emergency.heat.zip)
og

**Comment by PeteRager** [comment]
Thanks, that gave me what I needed.  

Home Assistant does not support "Emergency Heat" as a valid HVAC Mode and they do not allow us to create are our Modes.   Home Assistant does support aux_heat and treats this as something that can be turned on / off.  Here's a picture of what that looks like from the climate card

![image](https://user-images.githubusercontent.com/76050312/140825963-33af1180-f261-4df2-bc1f-9ca8da4543d8.png)

Doing the integration that way would give us this:

climate.turn_aux_heat_on  / turn_aux_heat_off  (standard HA climate methods) - this is the switch in the picture.  Turning it On will put the Lennox Zone into Emergency Heat Mode.  Turning it off will put the Lennox Zone into Heat Mode.

climate.aux_heat (standard HA climate attribute) - this will be True if the zone is in emergency heat, False otherwise

climate.aux (custom climate attribute) - this will be True if the auxiliary heat is on, false otherwise.  This reflect the state of the Lennox aux attribute.

The aux_heat capability will only be enabled for S30s that have an outdoor heat pump and an indoor furnace.

Thoughts?

**Comment by highincolorado** [comment]
I noticed after the last fix that the history dropped the high temperature set point when the ac mode was not used, this was a good thing. 

Not sure under what situation the emergency heat would be used but having it in the integration looks good. Perhaps needed if the heat pump is suffering a malfunction and the high ambient lockout is in play. 

Would there be a possibility that the history would show what heat source is running or would that be something I would needs to build with grafana?

**Comment by PeteRager** [comment]
If I has a heat pump and was running off of generator power, I’d probably prefer to switch over to the gas furnace.   Utility load shedding is another use case.

You should be able to create a template sensor that reports the states you want and then record It.

three states:
Heat Pump Only - Heating or Cooling operation active AND aux is False
Heat Pump and Furnace - Heating operation active and aux is True and aux_heat (aka emergency heat) is False
Furnace Only - Heating Operation active, Aux is True and aux_heat is true
invalid - any other state

**Comment by highincolorado** [comment]
A valid reason for furnace only is cold temperatures, there is a low ambient lock out to stop the heat pump when there just isn’t any heat to be pumped from outdoors. Being in an area where sub zero (f) temperatures happen this is one of the things I was hoping to track. 

Will play with all my options when the next release hits.
Thanks

**Comment by highincolorado** [comment]
Caught the lockout:
![72E1BA3D-8B67-43CF-8197-18E1129C0B80](https://user-images.githubusercontent.com/60855018/140854626-c070d5c6-baca-4dfd-84b2-49b01c53fbaf.png)

Will look for it in the logs in the morning.

**Comment by PeteRager** [comment]
Very cool.  Yeah, find the status message for that and I’ll get it captured and available.

**Comment by PeteRager** [comment]
Here’s what Lennox says about it.  Hopefully there’s a simple status message, though this sounds like the system is comparing these low and high balance points (somewhere in that giant config document), to the outdoor temperature and animating the lockout icon from that comparison.  Searching for balance in the logs may be helpful

“This indicates that either the outdoor temperature
is above or below the balance point temperature settings. The low balance point setting prevents heat pump heating below the set point and back up heat will be used. Typically the default is 25°F (-4.0°C), but that setting can be adjusted by your dealer. At 25°F (-4.0°C) or below for example, only auxiliary heating (electric or gas) is used. If the high balance point is set to 50°F ( 10°C ) for example, which is also adjustable by your dealer, then auxiliary heat will not be allowed. Only heat pump heating will be used. Anytime the outdoor temperature is below or above the balance point temperature settings, the ambient lockout notice will appear on the home screen.”

**Comment by highincolorado** [comment]
Can you share the Lennox documentation you are using? I have searched unsuccessfully for anything on their api and would like to have a look at what you have found.

A few morning tasks to get done then I will dig into the logs.

Thanks

**Comment by PeteRager** [comment]
https://www.lennox.com/products/comfort-controls/thermostats/icomforts30

https://www.lennox.com/lib/pdfs/owners/icomfort/lennox_icomforts30_installation_manual_setup_guide.pdf

**Comment by highincolorado** [comment]
Ok using a couple of days data I think I found what signals the high and low lockouts in effect. I marked the file with comments at transition points. Looks like the text message is a 1 shot which is marked not active as it is sent but these alerts seem to line up nicely.
[Balance points.txt](https://github.com/PeteRager/lennoxs30/files/7515285/Balance.points.txt)

**Comment by PeteRager** [comment]
Interesting they do it through alerts.  That’s a part of the API we have not ventured into.  We should be able to turns these into Booleans that indicate if the alert is active.

**Comment by highincolorado** [comment]
I kept digging and what about "balancePoint"? Seems to be in my small dataset to be: 
low = low ambient 
mid = no lockout 
high = High ambient

**Comment by PeteRager** [comment]
Ok, those would be interesting to see also.

I think we are a few weeks out from getting this piece completed.   We are moving the config into the Home Assistant integration UI which is taking time.

**Comment by PeteRager** [comment]
I have this work mostly done and the next release will go out next week.  The one open item is processing the Alerts for the lockouts, I added a new issue #97 to track that and will work on it during the next release cycle.

**Comment by PeteRager** [comment]
In this release and should now work.  Open a new issue if there are issues.

https://github.com/PeteRager/lennoxs30/releases/tag/v0.1.3a
