### ISSUE TITLE
Http 502 Cloud misses changes

### ISSUE THREAD

**Issue by PeteRager** [PeteRager/lennoxs30#90]
When a local connection is established and a cloud connection is established.  The cloud connection may not receive all messages and can become out of sync.

**Comment by deviantintegral** [comment]
Does it eventually solve itself, or do you have to reboot the thermostat or disable local polling to fix it?

**Comment by PeteRager** [comment]
It does seem to self-correct, but the sync issue seems to be persistent.  I first noticed it, when I turned HVAC Off and put the fan in circulate mode from HA with Local Connection; and I did not see the change in the HA with Cloud Connection.  There was an error logged about that time in the HA cloud connection log.

This view is of the Fan from the Cloud Connected HA and the bottom from the Local Connected HA.  You can see the local connected one is very regular, where-as the Cloud Connected one appears to be intermittently missing the Fan On or Fan Off messages.

![image](https://user-images.githubusercontent.com/76050312/141324429-a2740cd3-d6d4-42af-a3e0-a46ab6bb5e8a.png)


![image](https://user-images.githubusercontent.com/76050312/141324387-34f73465-3a99-4bbf-a730-c54bf25a3c3b.png)

**Comment by PeteRager** [comment]
Appears the problems started on 11/4.  I was running and old version of the integration in Production, so I updated to 0.1.2, I also set the app_id instead of using randomly generated (this is what we are recommending).  I will see if the re-start / re-establishment of the subscription corrects the intermittency or not.

**Comment by PeteRager** [comment]
With the restart still seeing missing messages in Cloud, but they correspond to errors that are getting logged:

2021-11-11 11:24:57 DEBUG (MainThread) [custom_components.lennoxs30] messagePump_task running
2021-11-11 11:27:08 INFO (MainThread) [lennoxs30api.s30api_async] messagePump failed response http_code [502]
2021-11-11 11:27:08 DEBUG (MainThread) [custom_components.lennoxs30] messagePump_task - S30Exception (S30Exception(...), 'messagePump failed response http_code [502]')
2021-11-11 11:27:23 DEBUG (MainThread) [custom_components.lennoxs30] messagePump_task running

The code treats a 502 as an intermittent error and unless several errors occur in a row it does not try to re-sync the connection.  It now appears that a 502 (internal server error) does result in a lost message.

**Comment by PeteRager** [comment]
Stopped the HA running local polling, same 502 errors occurring on Cloud.  Power Cycled the S30, same 502s occurring on Cloud. Hence this appears to be a Lennox Cloud issue.  Will keep monitoring to see if it resolves.  Anyone else using Cloud getting 502s?

![image](https://user-images.githubusercontent.com/76050312/141351542-d18fd7ed-89eb-4d34-91f3-0cb701c8b99e.png)

**Comment by deviantintegral** [comment]
I enabled local polling yesterday, and so far I have zero 5xx responses, and it looks like the only connection interruptions are when I restarted HA.

**Comment by PeteRager** [comment]
I’m still unable to obtain a stable cloud connection with 0.1.2.  Get 502s every 10-20 minutes.  I don’t know why this is affecting only my account.  The mobile app also fails to load most of the time.  So I think this on the Lennox side.   Since I have no fix, I’ve switched my prod system over to use the local connection, which is working fine.  If you encounter this issue, that is the current recommendation.

**Comment by PeteRager** [comment]
> I enabled local polling yesterday, and so far I have zero 5xx responses, and it looks like the only connection interruptions are when I restarted HA.

That’s good news.  Perplexed as to why this only affect my cloud connection, but I’ve seen that before with other users….

**Comment by PeteRager** [comment]
The issue seems to be resolved.  I believe it was related to running the local connection with a zero delay between polls and running the cloud connection with an internally specified longpolldelay of 15.  Once I changed these the problems seem to have gone away - or perhaps Lennox fixed something in their cloud system.
