### ISSUE TITLE
Regarding coolCoast and heatCoast values and their meaning

### ISSUE THREAD

**Issue by hypyke** [PeteRager/lennoxs30#93]
Sorry if someone already added this. It was requested in the READ ME

![image](https://user-images.githubusercontent.com/3076893/141870770-d4119b8b-cfd1-4f58-9290-8cfefefa7c40.png)
#

**Comment by PeteRager** [comment]
Thank you!  Will update.   These fields will be in 0.1.3 - looks like our docs are ahead of the release…

**Comment by PeteRager** [comment]
Docs have been updated for 0.1.3 release - coming out this upcoming week
