### ISSUE TITLE
Inverter Power Sensor - exception - when no data

### ISSUE THREAD

**Issue by PeteRager** [PeteRager/lennoxs30#94]
I enabled this sensor; when not connected locally and it crashes here.  We should catch this error and/or check the attributes first and return "None" to HA.

2021-11-17 15:17:29 ERROR (MainThread) [homeassistant.components.sensor] Error while setting up lennoxs30 platform for sensor
Traceback (most recent call last):
  File "/home/pete/core/homeassistant/helpers/entity_platform.py", line 257, in _async_setup_platform
    await asyncio.gather(*pending)
  File "/home/pete/core/homeassistant/helpers/entity_platform.py", line 382, in async_add_entities
    await asyncio.gather(*tasks)
  File "/home/pete/core/homeassistant/helpers/entity_platform.py", line 607, in _async_add_entity
    await entity.add_to_platform_finish()
  File "/home/pete/core/homeassistant/helpers/entity.py", line 709, in add_to_platform_finish
    self.async_write_ha_state()
  File "/home/pete/core/homeassistant/helpers/entity.py", line 480, in async_write_ha_state
    self._async_write_ha_state()
  File "/home/pete/core/homeassistant/helpers/entity.py", line 513, in _async_write_ha_state
    state = self._stringify_state()
  File "/home/pete/core/homeassistant/helpers/entity.py", line 486, in _stringify_state
    if (state := self.state) is None:
  File "/home/pete/core/config/custom_components/lennoxs30/sensor.py", line 313, in state
    return int(float(self._system.diagInverterInputVoltage) * float(self._system.diagInverterInputCurrent))
AttributeError: 'lennox_system' object has no attribute 'diagInverterInputVoltage'

**Comment by PeteRager** [comment]
@hufman - can you take a look at this?

**Comment by hufman** [comment]
That specific error is because the underlying lennoxs30api library is not the trunk version which [includes that parameter](https://github.com/PeteRager/lennoxs30api/blob/a276f6ffcfbf440efc06fb54e62b19364e847810/lennoxs30api/s30api_async.py#L751). The HA plugin catches the error about a None value as part of the [ValueError handling](https://github.com/PeteRager/lennoxs30/blob/f44738a4c0b1f36d6d45d5ee3f93027cb8dee706/custom_components/lennoxs30/sensor.py#L300).
Should I add handling to gracefully handle the older lennoxs30api library versions which don't include support for this data?

**Comment by PeteRager** [comment]
Apologies.  Yes you are right, I don’t have the latest.   I’ll pull that in the AM.

**Comment by PeteRager** [comment]
I had my python libraries in the HA venv pointing to the pypi install...anyways driver error... :-(

2021-11-18 09:32:46 WARNING (MainThread) [custom_components.lennoxs30.sensor] state myname [SageHouse_inverter_energy] failed: could not convert string to float: 'waiting...'

![image](https://user-images.githubusercontent.com/76050312/142436303-f5a4d8ea-5d44-410f-9631-248712d88f15.png)

Do you think we should check for this "waiting..." string and return None and/or log an info/debug message?

**Comment by hufman** [comment]
Oh good, that means the ValueError exception handling worked, that's where that log message `state myname` is [coming from](https://github.com/PeteRager/lennoxs30/blob/f44738a4c0b1f36d6d45d5ee3f93027cb8dee706/custom_components/lennoxs30/sensor.py#L301).
We could add a specific check for `waiting...` or None to skip the parsing and return None, to quiet the logs down a bit. My quick thought originally was that the logs would have the message (perhaps too many repeatedly? or perhaps the dirty field tracking would keep it quiet?) about why the inverter power is None, but it looks like the raw diagnostic values are being exported in the attributes, which might be enough of a debugging clue for users who enable the sensor without the needed hardware.

**Comment by PeteRager** [comment]
Good questions.  Here’s some thoughts on expected behavior. 

My system does have an inverter but it’s probably never turned on since I rebooted the S30.  I also do not have diagnostics turned on.  I’m also using the cloud connection. 

So it’s unclear what the root cause is and hence what message we should display to the user.

If “waiting” is sent because diagnostics are not active - then a message saying “S30 diagnostics must be turned on before using this sensor - consult read me” would be helpful.

If “waiting” is sent because the inverter has never turned on. Then we may want to translate that to a 0.0 return value since it indicates no power usage.

I don’t think it’s a cloud connection thing since that seems to be just a proxy/gateway between cloud and the S30 via some type of tunnel.  

I’ll look at some old cloud logs / JSON test file to see if I ever got a value for this.

**Comment by PeteRager** [comment]
Here's what I think the answer could be:

1.  During sensor initialization we should check the system.diagLevel and log a warning if diagLevel is 0 or None.  The warning message would instruct the user to turn on diags when using this sensor and consult the readme for how to do this.
2.  Since waiting... is a valid value, we should not log an warning and instead return None.  Alternatively, we could return 0

I don't know if waiting... is because I don't have diagnostics on.  I'm running a duration test for local with latest build and do not want to disrupt that.  I do get "waiting" from both local and cloud connections.

From mining other logs I have from users that sent them to me.  It appears that the diagnostic sections are equipment dependent.  For example, a heat only furnace does not have an inverter and hence that diagnostic never appears.  So this also means we could get a None value.

3.  If either value is None we should return a None

Thoughts?
